
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class Frm90sSub extends javax.swing.JFrame {
    
    //Declare and initialize variables
    String artist = Frm90sForm.ninetiesSub;
    int sub;
    String musicPath;

    /**
     * Creates new form Frm90sSub
     */
    public Frm90sSub() {
        initComponents();
    }
    
    //Method to carry String variable value to JLabel
    public Frm90sSub(String para){
        initComponents();
        
        lblMainArtist.setText(para);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        btnBackTo90s = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMainArtist = new javax.swing.JLabel();
        lblSubArtist = new javax.swing.JLabel();
        btnPlaySub = new javax.swing.JButton();
        lblSubArtistCode = new javax.swing.JLabel();
        lblDidYouLike = new javax.swing.JLabel();
        btnLikeYes = new javax.swing.JButton();
        btnNoLike = new javax.swing.JButton();
        lblPromptNextFrm = new javax.swing.JLabel();
        btnGenerateNew = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(202, 74, 31));

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        btnBackTo90s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackTo90s.setForeground(new java.awt.Color(255, 255, 255));
        btnBackTo90s.setText("90s");
        btnBackTo90s.setContentAreaFilled(false);
        btnBackTo90s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTo90sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBackTo90s)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addGap(18, 18, 18)
                .addComponent(btnBackTo90s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW ARTIST LIKE");

        lblMainArtist.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblMainArtist.setForeground(new java.awt.Color(204, 51, 0));
        lblMainArtist.setText("MAIN ARTIST");

        lblSubArtist.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        lblSubArtist.setForeground(new java.awt.Color(255, 255, 255));
        lblSubArtist.setText("SUB ARTIST");

        btnPlaySub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-40.png"))); // NOI18N
        btnPlaySub.setContentAreaFilled(false);
        btnPlaySub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySubActionPerformed(evt);
            }
        });

        lblDidYouLike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDidYouLike.setForeground(new java.awt.Color(255, 255, 255));
        lblDidYouLike.setText("Do you like this new artist?");

        btnLikeYes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLikeYes.setForeground(new java.awt.Color(255, 255, 255));
        btnLikeYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-up-50.png"))); // NOI18N
        btnLikeYes.setContentAreaFilled(false);
        btnLikeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeYesActionPerformed(evt);
            }
        });

        btnNoLike.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNoLike.setForeground(new java.awt.Color(255, 255, 255));
        btnNoLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-down-50.png"))); // NOI18N
        btnNoLike.setContentAreaFilled(false);
        btnNoLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoLikeActionPerformed(evt);
            }
        });

        lblPromptNextFrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromptNextFrm.setForeground(new java.awt.Color(255, 255, 255));
        lblPromptNextFrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptNextFrm.setText("(message)");

        btnGenerateNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-memories-100 (1).png"))); // NOI18N
        btnGenerateNew.setContentAreaFilled(false);
        btnGenerateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateNewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE A NEW ARTIST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSubArtist)
                                .addGap(0, 0, 0)
                                .addComponent(btnPlaySub))
                            .addComponent(lblMainArtist)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSubArtistCode, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnGenerateNew)
                                                .addGap(45, 45, 45))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDidYouLike)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16))))
                                    .addComponent(lblPromptNextFrm, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblMainArtist)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblSubArtist))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnPlaySub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubArtistCode, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateNew)
                        .addGap(40, 40, 40)
                        .addComponent(lblDidYouLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPromptNextFrm)
                        .addGap(120, 120, 120))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Make Menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Make Genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnBackTo90sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTo90sActionPerformed
        //Make 90s form visible
        new Frm90sForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackTo90sActionPerformed

    private void btnPlaySubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySubActionPerformed
        //Call playMusic method from main class
        playMusic(musicPath);
        
        //Make preference question visible
        btnLikeYes.setVisible(true);
        btnNoLike.setVisible(true);
        lblDidYouLike.setVisible(true);
    }//GEN-LAST:event_btnPlaySubActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Sets JLabel to String value from genre form
        lblMainArtist.setText(artist);
        
        //Randomly generates number depending on main artist chosen
        switch (artist) {
            case "MARIAH CAREY": sub = (int)(3*Math.random()+0); break;
            case "SWV": sub = (int)(3*Math.random()+3); break;
            case "BACKSTREET BOYS": sub = (int)(3*Math.random()+6); break;
            case "SPICE GIRLS": sub = (int)(3*Math.random()+9); break;
            case "TLC": sub = (int)(3*Math.random()+12); break;
            case "NSYNC": sub = (int)(3*Math.random()+15); break;
            case "CELINE DION": sub = (int)(3*Math.random()+18); break;
            case "DESTINY'S CHILD": sub = (int)(3*Math.random()+21); break;
            case "NIRVANA": sub = (int)(3*Math.random()+24); break;
            case "ALANIS MORISSETTE": sub = (int)(3*Math.random()+27); break;
            default:
                break;
        }
        
        //Declare and initialize String array for genre subartists
        String [] nineties = new String [30];
        
        //Assign values to String array for genre subartists
        nineties [0] = "BRANDY";
        nineties [1] = "TONI BRAXTON";
        nineties [2] = "MONICA";
        nineties [3] = "JODECI";
        nineties [4] = "SOUL FOR REAL";
        nineties [5] = "CHANGING FACES";
        nineties [6] = "NKOTB";
        nineties [7] = "BOYZONE";
        nineties [8] = "AARON CARTER";
        nineties [9] = "ALL SAINTS";
        nineties [10] = "GERI HALLIWELL";
        nineties [11] = "SUGABABES";
        nineties [12] = "EN VOGUE";
        nineties [13] = "AALIYAH";
        nineties [14] = "MYA";
        nineties [15] = "O-TOWN";
        nineties [16] = "HANSON";
        nineties [17] = "M2M";
        nineties [18] = "CHER";
        nineties [19] = "LARA FABIAN";
        nineties [20] = "BARABRA STREISAND";
        nineties [21] = "KELLY ROWLAND";
        nineties [22] = "KERI HILSON";
        nineties [23] = "AMERIE";
        nineties [24] = "SOUNDGARDEN";
        nineties [25] = "ALICE IN CHAINS";
        nineties [26] = "HOLE";
        nineties [27] = "NATALIE IMBRUGLIA";
        nineties [28] = "DIDO";
        nineties [29] = "JEWEL";
        
        //Form output depending on randomly generated number
        switch (sub){
            case 0:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Brandy.wav";
                ImageIcon codeBrandy = new ImageIcon("src\\codes\\Brandy.jpg");
                lblSubArtistCode.setIcon(codeBrandy);
                break;
            case 1:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\ToniBraxton.wav";
                ImageIcon codeToniBraxton = new ImageIcon("src\\codes\\ToniBraxton.jpg");
                lblSubArtistCode.setIcon(codeToniBraxton);
                break;
            case 2:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Monica.wav";
                ImageIcon codeMonica = new ImageIcon("src\\codes\\Monica.jpg");
                lblSubArtistCode.setIcon(codeMonica);
                break;
                
            case 3:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Jodeci.wav";
                ImageIcon codeJodeci = new ImageIcon("src\\codes\\Jodeci.jpg");
                lblSubArtistCode.setIcon(codeJodeci);
                break;  
            case 4:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\SoulForReal.wav";
                ImageIcon codeSoulForReal = new ImageIcon("src\\codes\\SoulForReal.jpg");
                lblSubArtistCode.setIcon(codeSoulForReal);
                break;     
            case 5:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\ChangingFaces.wav";
                ImageIcon codeChangingFaces = new ImageIcon("src\\codes\\ChangingFaces.jpg");
                lblSubArtistCode.setIcon(codeChangingFaces);
                break;   
                
            case 6:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\NewKidsOnTheBlock.wav";
                ImageIcon codeNewKidsOnTheBlock = new ImageIcon("src\\codes\\NewKidsOnTheBlock.jpg");
                lblSubArtistCode.setIcon(codeNewKidsOnTheBlock);
                break;  
            case 7:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Boyzone.wav";
                ImageIcon codeBoyzone = new ImageIcon("src\\codes\\Boyzone.jpg");
                lblSubArtistCode.setIcon(codeBoyzone);
                break;     
            case 8:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\AaronCarter.wav";
                ImageIcon codeAaronCarter = new ImageIcon("src\\codes\\AaronCarter.jpg");
                lblSubArtistCode.setIcon(codeAaronCarter);
                break;
                
            case 9:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\AllSaints.wav";
                ImageIcon codeAllSaints = new ImageIcon("src\\codes\\AllSaints.jpg");
                lblSubArtistCode.setIcon(codeAllSaints);
                break;  
            case 10:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\GeriHalliwell.wav";
                ImageIcon codeGeriHalliwell = new ImageIcon("src\\codes\\GeriHalliwell.jpg");
                lblSubArtistCode.setIcon(codeGeriHalliwell);
                break;     
            case 11:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Sugababes.wav";
                ImageIcon codeSugababes = new ImageIcon("src\\codes\\Sugababes.jpg");
                lblSubArtistCode.setIcon(codeSugababes);
                break;     
                
            case 12:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\EnVogue.wav";
                ImageIcon codeEnVogue = new ImageIcon("src\\codes\\EnVogue.jpg");
                lblSubArtistCode.setIcon(codeEnVogue);
                break;  
            case 13:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Aaliyah.wav";
                ImageIcon codeAaliyah = new ImageIcon("src\\codes\\Aaliyah.jpg");
                lblSubArtistCode.setIcon(codeAaliyah);
                break;     
            case 14:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Mya.wav";
                ImageIcon codeMya = new ImageIcon("src\\codes\\Mya.jpg");
                lblSubArtistCode.setIcon(codeMya);
                break;      
                
            case 15:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\OTown.wav";
                ImageIcon codeOTown = new ImageIcon("src\\codes\\OTown.jpg");
                lblSubArtistCode.setIcon(codeOTown);
                break;  
            case 16:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Hanson.wav";
                ImageIcon codeHanson = new ImageIcon("src\\codes\\Hanson.jpg");
                lblSubArtistCode.setIcon(codeHanson);
                break;     
            case 17:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\M2M.wav";
                ImageIcon codeM2M = new ImageIcon("src\\codes\\M2M.jpg");
                lblSubArtistCode.setIcon(codeM2M);
                break;      
                
            case 18:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Cher.wav";
                ImageIcon codeCher = new ImageIcon("src\\codes\\Cher.jpg");
                lblSubArtistCode.setIcon(codeCher);
                break;  
            case 19:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\LaraFabian.wav";
                ImageIcon codeLaraFabian = new ImageIcon("src\\codes\\LaraFabian.jpg");
                lblSubArtistCode.setIcon(codeLaraFabian);
                break;     
            case 20:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Barabra.wav";
                ImageIcon codeBarabraStreisand = new ImageIcon("src\\codes\\Barabra.jpg");
                lblSubArtistCode.setIcon(codeBarabraStreisand);
                break;     
                
            case 21:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\KellyRowland.wav";
                ImageIcon codeKellyRowland = new ImageIcon("src\\codes\\KellyRowland.jpg");
                lblSubArtistCode.setIcon(codeKellyRowland);
                break;  
            case 22:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\KeriHilson.wav";
                ImageIcon codeKeriHilson = new ImageIcon("src\\codes\\KeriHilson.jpg");
                lblSubArtistCode.setIcon(codeKeriHilson);
                break;     
            case 23:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Amerie.wav";
                ImageIcon codeAmerie = new ImageIcon("src\\codes\\Amerie.jpg");
                lblSubArtistCode.setIcon(codeAmerie);
                break;  
                
            case 24:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Soundgarden.wav";
                ImageIcon codeSoundgarden = new ImageIcon("src\\codes\\Soundgarden.jpg");
                lblSubArtistCode.setIcon(codeSoundgarden);
                break;  
            case 25:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\AliceinChains.wav";
                ImageIcon codeAliceinChains = new ImageIcon("src\\codes\\AliceinChains.jpg");
                lblSubArtistCode.setIcon(codeAliceinChains);
                break;     
            case 26:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Hole.wav";
                ImageIcon codeHole = new ImageIcon("src\\codes\\Hole.jpg");
                lblSubArtistCode.setIcon(codeHole);
                break;    
                
            case 27:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\NatalieImbruglia.wav";
                ImageIcon codeNatalieImbruglia = new ImageIcon("src\\codes\\NatalieImbruglia.jpg");
                lblSubArtistCode.setIcon(codeNatalieImbruglia);
                break;  
            case 28:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Dido.wav";
                ImageIcon codeDido = new ImageIcon("src\\codes\\Dido.jpg");
                lblSubArtistCode.setIcon(codeDido);
                break;     
            case 29:
                lblSubArtist.setText(nineties[sub]);
                musicPath = "src\\Audios\\Jewel.wav";
                ImageIcon codeJewel = new ImageIcon("src\\codes\\Jewel.jpg");
                lblSubArtistCode.setIcon(codeJewel);
                break;        
            default:
                break;
        }
        
        //Make preference question not visible
        btnLikeYes.setVisible(false);
        btnNoLike.setVisible(false);
        lblDidYouLike.setVisible(false);
        lblPromptNextFrm.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnLikeYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeYesActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Great! Remember to scan their code on Spotify!");
    }//GEN-LAST:event_btnLikeYesActionPerformed

    private void btnNoLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoLikeActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Don't worry! There's lots more for you to find!");
    }//GEN-LAST:event_btnNoLikeActionPerformed

    private void btnGenerateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateNewActionPerformed
        //Makes sub genre form visible again
        new Frm90sSub().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm90sSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm90sSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm90sSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm90sSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm90sSub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackTo90s;
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnGenerateNew;
    private javax.swing.JButton btnLikeYes;
    private javax.swing.JButton btnNoLike;
    private javax.swing.JButton btnPlaySub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDidYouLike;
    private javax.swing.JLabel lblMainArtist;
    private javax.swing.JLabel lblPromptNextFrm;
    private javax.swing.JLabel lblSubArtist;
    private javax.swing.JLabel lblSubArtistCode;
    // End of variables declaration//GEN-END:variables
}
