
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 073630006
 */
public class FrmCountrySub extends javax.swing.JFrame {

    //Declare and initialize variables
    String artist = FrmCountryForm.countrySub;
    String musicFile;
    int sub;
    
    /**
     * Creates new form FrmCountrySub
     */
    public FrmCountrySub() {
        initComponents();
    }

    //Method to carry String variable value to JLabel
    public FrmCountrySub(String para){
        initComponents();
        
        lblMainArtistName.setText(para);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSimilarName = new javax.swing.JLabel();
        lblMainArtistName = new javax.swing.JLabel();
        lblSimilarCode = new javax.swing.JLabel();
        btnPlaySong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        btnBackToCount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerateNew = new javax.swing.JButton();
        lblDidYouLike = new javax.swing.JLabel();
        btnLikeYes = new javax.swing.JButton();
        btnNoLike = new javax.swing.JButton();
        lblPromptNextFrm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(239, 200, 48));

        lblSimilarName.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        lblSimilarName.setForeground(new java.awt.Color(255, 255, 255));
        lblSimilarName.setText("SUB ARTIST");

        lblMainArtistName.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblMainArtistName.setForeground(new java.awt.Color(217, 178, 24));
        lblMainArtistName.setText("MAIN ARTIST");

        btnPlaySong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-40.png"))); // NOI18N
        btnPlaySong.setContentAreaFilled(false);
        btnPlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySongActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(230, 187, 17));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        btnBackToCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToCount.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToCount.setText("COUNTRY");
        btnBackToCount.setContentAreaFilled(false);
        btnBackToCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(btnBackToCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackToCount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW ARTIST LIKE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE A NEW ARTIST");

        btnGenerateNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-memories-100 (1).png"))); // NOI18N
        btnGenerateNew.setContentAreaFilled(false);
        btnGenerateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateNewActionPerformed(evt);
            }
        });

        lblDidYouLike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDidYouLike.setForeground(new java.awt.Color(255, 255, 255));
        lblDidYouLike.setText("Do you like this new artist?");

        btnLikeYes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLikeYes.setForeground(new java.awt.Color(255, 255, 255));
        btnLikeYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-up-50.png"))); // NOI18N
        btnLikeYes.setContentAreaFilled(false);
        btnLikeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeYesActionPerformed(evt);
            }
        });

        btnNoLike.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNoLike.setForeground(new java.awt.Color(255, 255, 255));
        btnNoLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-down-50.png"))); // NOI18N
        btnNoLike.setContentAreaFilled(false);
        btnNoLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoLikeActionPerformed(evt);
            }
        });

        lblPromptNextFrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromptNextFrm.setForeground(new java.awt.Color(255, 255, 255));
        lblPromptNextFrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptNextFrm.setText("(message)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSimilarName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaySong))
                    .addComponent(lblMainArtistName)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSimilarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGenerateNew)
                                        .addGap(45, 45, 45))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDidYouLike)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addComponent(lblPromptNextFrm, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblMainArtistName)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblSimilarName)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaySong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSimilarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateNew)
                        .addGap(40, 40, 40)
                        .addComponent(lblDidYouLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPromptNextFrm)
                        .addGap(120, 120, 120))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySongActionPerformed
        //Call playMusic method from main class
        playMusic(musicFile);
        
        //Make preference question visible
        btnLikeYes.setVisible(true);
        btnNoLike.setVisible(true);
        lblDidYouLike.setVisible(true);
    }//GEN-LAST:event_btnPlaySongActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Make menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Make genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnBackToCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToCountActionPerformed
        //Make country form visible
        new FrmCountryForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToCountActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //Sets JLabel to String value from genre form
        lblMainArtistName.setText(artist);
        
        //Randomly generates number depending on main artist chosen
        switch (artist)  {
            case "THOMAS RHETT": sub = (int)(3 * Math.random() + 0); break;
            case "KACEY MUSGRAVES": sub = (int)(3 * Math.random() + 3); break;
            case "LUKE BRYAN": sub = (int)(3 * Math.random() + 6); break;
            case "SAM HUNT": sub = (int)(3 * Math.random() + 9); break;
            case "FLORIDA GEORGIA LINE": sub = (int)(3 * Math.random() + 12); break;
            case "LITTLE BIG TOWN": sub = (int)(3 * Math.random() + 15); break;
            case "BRETT ELDREDGE": sub = (int)(3 * Math.random() + 18); break;
            case "HIGH VALLEY": sub = (int)(3 * Math.random() + 21); break;
            case "BRAD PAISLEY": sub = (int)(3 * Math.random() + 24); break;
            case "JASON ALDEAN": sub = (int)(3 * Math.random() + 27); break;
        }   
        
        //Declare and initialize String array for genre subartists
        String [] count = new String [30];
        
        //Assign values to String array for genre subartists
        count[0] = "JON PARDI";
        count[1] = "DUSTIN LYNCH";
        count[2] = "JAKE OWEN";
        count[3] = "MAREN MORRIS";
        count[4] = "MIRANDA LAMBERT";
        count[5] = "ELI YOUNG BAND";
        count[6] = "RASCAL FLATTS";
        count[7] = "BLAKE SHELTON";
        count[8] = "KEITH URBAN";
        count[9] = "COLE SWINDELL";
        count[10] = "KANE BROWN";
        count[11] = "OLD DOMINION";
        count[12] = "DIERKS BENTLEY";
        count[13] = "BILLY CURRINGTON";
        count[14] = "CHASE RICE";
        count[15] = "SUGARLAND";
        count[16] = "LADY ANTEBELLUM";
        count[17] = "THE BAND PERRY";
        count[18] = "LEE BRICE";
        count[19] = "WALKER HAYES";
        count[20] = "HUNTER HAYES";
        count[21] = "CANAAN SMITH";
        count[22] = "ERIC PASLAY";
        count[23] = "KIP MOORE";
        count[24] = "TRACE ADKINS";
        count[25] = "JOE NICHOLS";
        count[26] = "LONESTAR";
        count[27] = "CHRIS YOUNG";
        count[28] = "BRANTLEY GILBERT";
        count[29] = "CHRIS CAGLE";
        
        //Assigns spotify code images to variable names
        ImageIcon codePardi = new ImageIcon("src\\codes\\JonPardi.jpg");
        ImageIcon codeLynch = new ImageIcon("src\\codes\\DustinLynch.jpg");
        ImageIcon codeOwen = new ImageIcon("src\\codes\\JakeOwen.jpg");
        ImageIcon codeMorris = new ImageIcon("src\\codes\\MarenMorris.jpg");
        ImageIcon codeLambert = new ImageIcon("src\\codes\\MirandaLambert.jpg");
        ImageIcon codeEliYoung= new ImageIcon("src\\codes\\EliYoungBand.jpg");
        ImageIcon codeRascal = new ImageIcon("src\\codes\\RascalFlatts.jpg");
        ImageIcon codeShelton = new ImageIcon("src\\codes\\BlakeShelton.jpg");
        ImageIcon codeUrban = new ImageIcon("src\\codes\\KeithUrban.jpg");
        ImageIcon codeSwindell = new ImageIcon("src\\codes\\ColeSwindell.jpg");
        ImageIcon codeBrown = new ImageIcon("src\\codes\\KaneBrown.jpg");
        ImageIcon codeDominion = new ImageIcon("src\\codes\\OldDominion.jpg");
        ImageIcon codeBentley = new ImageIcon("src\\codes\\DierksBentley.jpg");
        ImageIcon codeCurrington = new ImageIcon("src\\codes\\BillyCurrington.jpg");
        ImageIcon codeRice = new ImageIcon("src\\codes\\ChaseRice.jpg");
        ImageIcon codeSugarland = new ImageIcon("src\\codes\\Sugarland.jpg");
        ImageIcon codeAntebellum = new ImageIcon("src\\codes\\LadyAntebellum.jpg");
        ImageIcon codeBandPerry = new ImageIcon("src\\codes\\TheBandPerry.jpg");
        ImageIcon codeBrice = new ImageIcon("src\\codes\\LeeBrice.jpg");
        ImageIcon codeWHayes = new ImageIcon("src\\codes\\WalkerHayes.jpg");
        ImageIcon codeHHayes = new ImageIcon("src\\codes\\HunterHayes.jpg");
        ImageIcon codeSmith = new ImageIcon("src\\codes\\CanaanSmith.jpg");
        ImageIcon codePaslay = new ImageIcon("src\\codes\\EricPaslay.jpg");
        ImageIcon codeMoore = new ImageIcon("src\\codes\\KipMoore.jpg");
        ImageIcon codeAdkins = new ImageIcon("src\\codes\\TraceAdkins.jpg");
        ImageIcon codeNichols = new ImageIcon("src\\codes\\JoeNichols.jpg");
        ImageIcon codeLonestar = new ImageIcon("src\\codes\\Lonestar.jpg");
        ImageIcon codeYoung = new ImageIcon("src\\codes\\ChrisYoung.jpg");
        ImageIcon codeGilbert = new ImageIcon("src\\codes\\BrantleyGilbert.jpg");
        ImageIcon codeCagle = new ImageIcon("src\\codes\\ChrisCagle.jpg");
        
        //Form output depending on randomly generated number
        switch (sub){
            case 0: lblSimilarName.setText(String.valueOf(count[0]));
                    lblSimilarCode.setIcon(codePardi); 
                    musicFile = "src\\audios\\JonPardi.wav"; break;
            case 1: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeLynch); 
                    musicFile = "src\\audios\\DustinLynch.wav"; break;
            case 2: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeOwen); 
                    musicFile = "src\\audios\\JakeOwen.wav"; break;
                    
            case 3: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeMorris); 
                    musicFile = "src\\audios\\MarenMorris.wav"; break;
            case 4: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeLambert); 
                    musicFile = "src\\audios\\MirandaLambert.wav"; break;
            case 5: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeEliYoung); 
                    musicFile = "src\\audios\\EliYoungBand.wav"; break;
                    
            case 6: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeRascal); 
                    musicFile = "src\\audios\\RascalFlatts.wav"; break;
            case 7: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeShelton); 
                    musicFile = "src\\audios\\BlakeShelton.wav"; break;        
            case 8: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeUrban); 
                    musicFile = "src\\audios\\KeithUrban.wav"; break; 
                    
            case 9: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeSwindell); 
                    musicFile = "src\\audios\\ColeSwindell.wav"; break;
            case 10: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeBrown); 
                    musicFile = "src\\audios\\KaneBrown.wav"; break;        
            case 11: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeDominion); 
                    musicFile = "src\\audios\\OldDominion.wav"; break; 
                    
            case 12: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeBentley); 
                    musicFile = "src\\audios\\DierksBentley.wav"; break;
            case 13: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeCurrington); 
                    musicFile = "src\\audios\\BillyCurrington.wav"; break;        
            case 14: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeRice); 
                    musicFile = "src\\audios\\ChaseRice.wav"; break;
                    
            case 15: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeSugarland); 
                    musicFile = "src\\audios\\Sugarland.wav"; break;
            case 16: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeAntebellum); 
                    musicFile = "src\\audios\\LadyAntebellum.wav"; break; 
            case 17: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeBandPerry); 
                    musicFile = "src\\audios\\TheBandPerry.wav"; break; 
                    
            case 18: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeBrice); 
                    musicFile = "src\\audios\\LeeBrice.wav"; break;
            case 19: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeWHayes); 
                    musicFile = "src\\audios\\WalkerHayes.wav"; break;
            case 20: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeHHayes); 
                    musicFile = "src\\audios\\HunterHayes.wav"; break; 
                    
            case 21: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeSmith); 
                    musicFile = "src\\audios\\CanaanSmith.wav"; break;
            case 22: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codePaslay); 
                    musicFile = "src\\audios\\EricPaslay.wav"; break; 
            case 23: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeMoore); 
                    musicFile = "src\\audios\\KipMoore.wav"; break;
                    
            case 24: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeAdkins); 
                    musicFile = "src\\audios\\TraceAdkins.wav"; break;
            case 25: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeNichols); 
                    musicFile = "src\\audios\\JoeNichols.wav"; break; 
            case 26: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeLonestar); 
                    musicFile = "src\\audios\\Lonestar.wav"; break; 
                    
            case 27: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeYoung); 
                    musicFile = "src\\audios\\ChrisYoung.wav"; break;
            case 28: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeGilbert); 
                    musicFile = "src\\audios\\BrantleyGilbert.wav"; break;        
            case 29: lblSimilarName.setText(String.valueOf(count[sub])); 
                    lblSimilarCode.setIcon(codeCagle); 
                    musicFile = "src\\audios\\ChrisCagle.wav"; break; 
        }
        
        //Make preference question not visible
        btnLikeYes.setVisible(false);
        btnNoLike.setVisible(false);
        lblDidYouLike.setVisible(false);
        lblPromptNextFrm.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnGenerateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateNewActionPerformed
        //Makes sub genre form visible again
        new FrmCountrySub().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateNewActionPerformed

    private void btnLikeYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeYesActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Great! Remember to scan their code on Spotify!");
    }//GEN-LAST:event_btnLikeYesActionPerformed

    private void btnNoLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoLikeActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Don't worry! There's lots more for you to find!");
    }//GEN-LAST:event_btnNoLikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCountrySub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCountrySub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCountrySub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCountrySub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCountrySub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToCount;
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnGenerateNew;
    private javax.swing.JButton btnLikeYes;
    private javax.swing.JButton btnNoLike;
    private javax.swing.JButton btnPlaySong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDidYouLike;
    private javax.swing.JLabel lblMainArtistName;
    private javax.swing.JLabel lblPromptNextFrm;
    private javax.swing.JLabel lblSimilarCode;
    private javax.swing.JLabel lblSimilarName;
    // End of variables declaration//GEN-END:variables
}
