
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author 073630006
 */
public class FrmHipHopSub extends javax.swing.JFrame {

    //Declare and initialize variables
    String artist = FrmHipHopForm.hipHopSub;
    String musicFile;
    int sub;
    
    /**
     * Creates new form FrmHipHopSubGood
     */
    public FrmHipHopSub() {
        initComponents();
    }

    //Method to carry String variable value to JLabel
    public FrmHipHopSub(String para){
        initComponents();
        
        lblMainArtistName.setText(para);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSimilarName = new javax.swing.JLabel();
        lblMainArtistName = new javax.swing.JLabel();
        lblSimilarCode = new javax.swing.JLabel();
        btnPlaySong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        btnBackToHipHop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerateNew = new javax.swing.JButton();
        lblDidYouLike = new javax.swing.JLabel();
        btnLikeYes = new javax.swing.JButton();
        btnNoLike = new javax.swing.JButton();
        lblPromptNextFrm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(211, 51, 51));

        lblSimilarName.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        lblSimilarName.setForeground(new java.awt.Color(255, 255, 255));
        lblSimilarName.setText("SUB ARTIST");

        lblMainArtistName.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblMainArtistName.setForeground(new java.awt.Color(153, 0, 0));
        lblMainArtistName.setText("MAIN ARTIST");

        btnPlaySong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-40.png"))); // NOI18N
        btnPlaySong.setContentAreaFilled(false);
        btnPlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySongActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(197, 16, 16));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        btnBackToHipHop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToHipHop.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHipHop.setText("HIPHOP");
        btnBackToHipHop.setContentAreaFilled(false);
        btnBackToHipHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHipHopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBackToHipHop, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addGap(18, 18, 18)
                .addComponent(btnBackToHipHop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW ARTIST LIKE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE A NEW ARTIST");

        btnGenerateNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-memories-100 (1).png"))); // NOI18N
        btnGenerateNew.setContentAreaFilled(false);
        btnGenerateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateNewActionPerformed(evt);
            }
        });

        lblDidYouLike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDidYouLike.setForeground(new java.awt.Color(255, 255, 255));
        lblDidYouLike.setText("Do you like this new artist?");

        btnLikeYes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLikeYes.setForeground(new java.awt.Color(255, 255, 255));
        btnLikeYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-up-50.png"))); // NOI18N
        btnLikeYes.setContentAreaFilled(false);
        btnLikeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeYesActionPerformed(evt);
            }
        });

        btnNoLike.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNoLike.setForeground(new java.awt.Color(255, 255, 255));
        btnNoLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-down-50.png"))); // NOI18N
        btnNoLike.setContentAreaFilled(false);
        btnNoLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoLikeActionPerformed(evt);
            }
        });

        lblPromptNextFrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromptNextFrm.setForeground(new java.awt.Color(255, 255, 255));
        lblPromptNextFrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptNextFrm.setText("(message)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSimilarName)
                                .addGap(0, 0, 0)
                                .addComponent(btnPlaySong))
                            .addComponent(lblMainArtistName)
                            .addComponent(jLabel1))
                        .addContainerGap(452, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSimilarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGenerateNew)
                                        .addGap(45, 45, 45))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDidYouLike)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addComponent(lblPromptNextFrm, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblMainArtistName)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblSimilarName)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaySong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSimilarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateNew)
                        .addGap(40, 40, 40)
                        .addComponent(lblDidYouLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPromptNextFrm)
                        .addGap(120, 120, 120))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySongActionPerformed
        //Call playMusic method from main class
        playMusic(musicFile);
        
        //Make preference question visible
        btnLikeYes.setVisible(true);
        btnNoLike.setVisible(true);
        lblDidYouLike.setVisible(true);
    }//GEN-LAST:event_btnPlaySongActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Make menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Make genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnBackToHipHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHipHopActionPerformed
         //Make hip hop form visible
        new FrmHipHopForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToHipHopActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
        //Sets JLabel to String value from genre form
        lblMainArtistName.setText(artist);
        
        //Randomly generates number depending on main artist chosen
        switch (artist)  {
            case "MEGAN THEE STALLION": sub = (int)(3 * Math.random() + 0); break;
            case "CARDI B": sub = (int)(3 * Math.random() + 3); break;
            case "LIL UZI VERT": sub = (int)(3 * Math.random() + 6); break;
            case "DRAKE": sub = (int)(3 * Math.random() + 9); break;
            case "XXXTENTACION": sub = (int)(3 * Math.random() + 12); break;
            case "DABABY": sub = (int)(3 * Math.random() + 15); break;
            case "MAC MILLER": sub = (int)(3 * Math.random() + 18); break;
            case "6IX9INE": sub = (int)(3 * Math.random() + 21); break;
            case "NICKI MINAJ": sub = (int)(3 * Math.random() + 24); break;
            case "A BOOGIE WIT DA HOODIE": sub = (int)(3 * Math.random() + 27); break;
        }   
        
        //Declare and initialize String array for genre subartists
        String [] hipHop = new String [30];
        
        //Assign values of String array for genre subartists
        hipHop[0] = "KASH DOLL";
        hipHop[1] = "DREEZY";
        hipHop[2] = "QUEEN KEY";
        hipHop[3] = "FLO MILLI";
        hipHop[4] = "CITY GIRLS";
        hipHop[5] = "CIARA";
        hipHop[6] = "LIL YACHTY";
        hipHop[7] = "KODAK BLACK";
        hipHop[8] = "NAV";
        hipHop[9] = "BIG SEAN";
        hipHop[10] = "TY DOLLA $IGN";
        hipHop[11] = "KENDRICK LAMAR";
        hipHop[12] = "LIL PUMP";
        hipHop[13] = "JUICE WRLD";
        hipHop[14] = "COOLIECUT";
        hipHop[15] = "RODDY RICCH";
        hipHop[16] = "YNW MELLY";
        hipHop[17] = "PLAYBOI CARTI";
        hipHop[18] = "WIZ KHALIFA";
        hipHop[19] = "A$AP ROCKY";
        hipHop[20] = "KEVIN ABSTRACT";
        hipHop[21] = "PNB ROCK";
        hipHop[22] = "LIL SKIES";
        hipHop[23] = "QUAVO";
        hipHop[24] = "STEFFLON DON";
        hipHop[25] = "TEYANA TAYLOR";
        hipHop[26] = "KELLY ROWLAND";
        hipHop[27] = "CALBOY";
        hipHop[28] = "YK OSIRIS";
        hipHop[29] = "LIL KEED";
        
        //Assigns spotify code images to variable names
        ImageIcon codeKash = new ImageIcon("src\\codes\\KashDoll.jpg");
        ImageIcon codeDreezy = new ImageIcon("src\\codes\\Dreezy.jpg");
        ImageIcon codeQueenKey = new ImageIcon("src\\codes\\QueenKey.jpg");
        ImageIcon codeFloMilli = new ImageIcon("src\\codes\\FloMilli.jpg");
        ImageIcon codeCityGirls = new ImageIcon("src\\codes\\CityGirls.jpg");
        ImageIcon codeCiara = new ImageIcon("src\\codes\\Ciara.jpg");
        ImageIcon codeYachty = new ImageIcon("src\\codes\\LilYachty.jpg");
        ImageIcon codeKodak = new ImageIcon("src\\codes\\KodakBlack.jpg");
        ImageIcon codeNav = new ImageIcon("src\\codes\\Nav.jpg");
        ImageIcon codeSean = new ImageIcon("src\\codes\\BigSean.jpg");
        ImageIcon codeDollaSign = new ImageIcon("src\\codes\\TyDollaSign.jpg");
        ImageIcon codeLamar = new ImageIcon("src\\codes\\KendrickLamar.jpg");
        ImageIcon codePump = new ImageIcon("src\\codes\\LilPump.jpg");
        ImageIcon codeJuice = new ImageIcon("src\\codes\\JuiceWRLD.jpg");
        ImageIcon codeCoolie = new ImageIcon("src\\codes\\Cooliecut.jpg");
        ImageIcon codeRicch = new ImageIcon("src\\codes\\RoddyRicch.jpg");
        ImageIcon codeMelly = new ImageIcon("src\\codes\\YNWMelly.jpg");
        ImageIcon codePlayboy = new ImageIcon("src\\codes\\PlayboyCarti.jpg");
        ImageIcon codeKhalifa = new ImageIcon("src\\codes\\WizKhalifa.jpg");
        ImageIcon codeRocky = new ImageIcon("src\\codes\\ASAPRocky.jpg");
        ImageIcon codeAbstract = new ImageIcon("src\\codes\\KevinAbstract.jpg");
        ImageIcon codePNB = new ImageIcon("src\\codes\\PNBRock.jpg");
        ImageIcon codeSkies = new ImageIcon("src\\codes\\LilSkies.jpg");
        ImageIcon codeQuavo = new ImageIcon("src\\codes\\Quavo.jpg");
        ImageIcon codeStefflon = new ImageIcon("src\\codes\\StefflonDon.jpg");
        ImageIcon codeTaylor = new ImageIcon("src\\codes\\TeyanaTaylor.jpg");
        ImageIcon codeRowland = new ImageIcon("src\\codes\\KellyRowland.jpg");
        ImageIcon codeCalboy = new ImageIcon("src\\codes\\Calboy.jpg");
        ImageIcon codeOsiris = new ImageIcon("src\\codes\\YKOsiris.jpg");
        ImageIcon codeKeed = new ImageIcon("src\\codes\\LilKeed.jpg");
        
        //Form output depending on randomly generated number
        switch (sub){
            //1st artist
            case 0: lblSimilarName.setText(hipHop[sub]);
                    lblSimilarCode.setIcon(codeKash); 
                    musicFile = "src\\audios\\KashDoll.wav"; break;
            case 1: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeDreezy); 
                    musicFile = "src\\audios\\Dreezy.wav"; break;
            case 2: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeQueenKey); 
                    musicFile = "src\\audios\\QueenKey.wav"; break;
            //2nd artist
            case 3: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeFloMilli); 
                    musicFile = "src\\audios\\FloMilli.wav"; break;
            case 4: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeCityGirls); 
                    musicFile = "src\\audios\\CityGirls.wav"; break;
            case 5: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeCiara); 
                    musicFile = "src\\audios\\Ciara.wav"; break;
            //3rd artist
            case 6: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeYachty); 
                    musicFile = "src\\audios\\LilYachty.wav"; break;
            case 7: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeKodak); 
                    musicFile = "src\\audios\\KodakBlack.wav"; break;        
            case 8: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeNav); 
                    musicFile = "src\\audios\\Nav.wav"; break;    
            //4th artist
            case 9: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeSean); 
                    musicFile = "src\\audios\\BigSean.wav"; break;
            case 10: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeDollaSign); 
                    musicFile = "src\\audios\\TyDollaSign.wav"; break;        
            case 11: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeLamar); 
                    musicFile = "src\\audios\\KendrickLamar.wav"; break; 
            //5th artist
            case 12: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codePump); 
                    musicFile = "src\\audios\\LilPump.wav"; break;
            case 13: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeJuice); 
                    musicFile = "src\\audios\\JuiceWRLD.wav"; break;        
            case 14: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeCoolie); 
                    musicFile = "src\\audios\\Cooliecut.wav"; break;  
            //6th artist
            case 15: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeRicch); 
                    musicFile = "src\\audios\\RoddyRicch.wav"; break;
            case 16: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeMelly); 
                    musicFile = "src\\audios\\YNWMelly.wav"; break;        
            case 17: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codePlayboy); 
                    musicFile = "src\\audios\\PlayboyCarti.wav"; break;
            //7th artist
            case 18: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeKhalifa); 
                    musicFile = "src\\audios\\WizKhalifa.wav"; break;
            case 19: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeRocky); 
                    musicFile = "src\\audios\\ASAPRocky.wav"; break;        
            case 20: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeAbstract); 
                    musicFile = "src\\audios\\KevinAbstract.wav"; break; 
            //8th artist
            case 21: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codePNB); 
                    musicFile = "src\\audios\\PNBRock.wav"; break;
            case 22: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeSkies); 
                    musicFile = "src\\audios\\LilSkies.wav"; break;        
            case 23: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeQuavo); 
                    musicFile = "src\\audios\\Quavo.wav"; break;
            //9th artist
            case 24: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeStefflon); 
                    musicFile = "src\\audios\\StefflonDon.wav"; break;
            case 25: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeTaylor); 
                    musicFile = "src\\audios\\TeyanaTaylor.wav"; break;        
            case 26: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeRowland); 
                    musicFile = "src\\audios\\KellyRowland.wav"; break; 
            //10th artist
            case 27: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeCalboy); 
                    musicFile = "src\\audios\\Calboy.wav"; break;
            case 28: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeOsiris); 
                    musicFile = "src\\audios\\YKOsiris.wav"; break;        
            case 29: lblSimilarName.setText(hipHop[sub]); 
                    lblSimilarCode.setIcon(codeKeed); 
                    musicFile = "src\\audios\\LilKeed.wav"; break; 
        }
        
        //Make preference question not visible
        btnLikeYes.setVisible(false);
        btnNoLike.setVisible(false);
        lblDidYouLike.setVisible(false);
        lblPromptNextFrm.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void btnGenerateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateNewActionPerformed
        //Makes sub genre form visible again
        new FrmHipHopSub().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateNewActionPerformed

    private void btnLikeYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeYesActionPerformed
        //Sets label to display message based on user input
        lblPromptNextFrm.setVisible(true);
        lblPromptNextFrm.setText("Great! Remember to scan their code on Spotify!");
    }//GEN-LAST:event_btnLikeYesActionPerformed

    private void btnNoLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoLikeActionPerformed
        //Sets label to display message based on user input
        lblPromptNextFrm.setVisible(true);
        lblPromptNextFrm.setText("Don't worry! There's lots more for you to find!");
    }//GEN-LAST:event_btnNoLikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHipHopSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHipHopSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHipHopSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHipHopSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHipHopSub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToHipHop;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnGenerateNew;
    private javax.swing.JButton btnLikeYes;
    private javax.swing.JButton btnNoLike;
    private javax.swing.JButton btnPlaySong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDidYouLike;
    private javax.swing.JLabel lblMainArtistName;
    private javax.swing.JLabel lblPromptNextFrm;
    private javax.swing.JLabel lblSimilarCode;
    private javax.swing.JLabel lblSimilarName;
    // End of variables declaration//GEN-END:variables

}
