
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class FrmRBSub extends javax.swing.JFrame {
    
    //Declare and initialize variables
    String artist = FrmRBForm.rbSub;
    int sub;
    String musicPath;

    /**
     * Creates new form FrmRBSub
     */
    public FrmRBSub() {
        initComponents();
    }
    
    //Method to carry String variable value to JLabel
    public FrmRBSub(String para){
        initComponents();
        
        lblMainArtist.setText(para);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        btnBackToRB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMainArtist = new javax.swing.JLabel();
        lblSubArtist = new javax.swing.JLabel();
        btnPlaySub = new javax.swing.JButton();
        lblSubArtistCode = new javax.swing.JLabel();
        btnGenerateNew = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDidYouLike = new javax.swing.JLabel();
        btnNoLike = new javax.swing.JButton();
        btnLikeYes = new javax.swing.JButton();
        lblPromptNextFrm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(172, 131, 50));

        jPanel2.setBackground(new java.awt.Color(147, 103, 15));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        btnBackToRB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToRB.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToRB.setText("R&B");
        btnBackToRB.setContentAreaFilled(false);
        btnBackToRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBackToRB)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addGap(18, 18, 18)
                .addComponent(btnBackToRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW ARTIST LIKE");

        lblMainArtist.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblMainArtist.setForeground(new java.awt.Color(147, 103, 15));
        lblMainArtist.setText("MAIN ARTIST");

        lblSubArtist.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        lblSubArtist.setForeground(new java.awt.Color(255, 255, 255));
        lblSubArtist.setText("SUB ARTIST");

        btnPlaySub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-40.png"))); // NOI18N
        btnPlaySub.setContentAreaFilled(false);
        btnPlaySub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySubActionPerformed(evt);
            }
        });

        btnGenerateNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-memories-100 (1).png"))); // NOI18N
        btnGenerateNew.setContentAreaFilled(false);
        btnGenerateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateNewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE A NEW ARTIST");

        lblDidYouLike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDidYouLike.setForeground(new java.awt.Color(255, 255, 255));
        lblDidYouLike.setText("Do you like this new artist?");

        btnNoLike.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNoLike.setForeground(new java.awt.Color(255, 255, 255));
        btnNoLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-down-50.png"))); // NOI18N
        btnNoLike.setContentAreaFilled(false);
        btnNoLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoLikeActionPerformed(evt);
            }
        });

        btnLikeYes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLikeYes.setForeground(new java.awt.Color(255, 255, 255));
        btnLikeYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-thumbs-up-50.png"))); // NOI18N
        btnLikeYes.setContentAreaFilled(false);
        btnLikeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeYesActionPerformed(evt);
            }
        });

        lblPromptNextFrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromptNextFrm.setForeground(new java.awt.Color(255, 255, 255));
        lblPromptNextFrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptNextFrm.setText("(message)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblSubArtist)
                                        .addGap(0, 0, 0)
                                        .addComponent(btnPlaySub))
                                    .addComponent(lblMainArtist))
                                .addGap(0, 438, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSubArtistCode, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnGenerateNew)
                                                .addGap(45, 45, 45))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDidYouLike)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16))))
                                    .addComponent(lblPromptNextFrm, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblMainArtist)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblSubArtist))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnPlaySub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblSubArtistCode, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateNew)
                        .addGap(40, 40, 40)
                        .addComponent(lblDidYouLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLikeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPromptNextFrm)
                        .addGap(120, 120, 120))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Sets JLabel to String value from genre form
        lblMainArtist.setText(artist);
        
        //Randomly generates number depending on main artist chosen
        switch (artist) {
            case "KHALID": sub = (int)(3*Math.random()+0); break;
            case "DANIEL CAESAR": sub = (int)(3*Math.random()+3); break;
            case "THE WEEKND": sub = (int)(3*Math.random()+6); break;
            case "FRANK OCEAN": sub = (int)(3*Math.random()+9); break;
            case "DOJA CAT": sub = (int)(3*Math.random()+12); break;
            case "TORY LANEZ": sub = (int)(3*Math.random()+15); break;
            case "JHENE AIKO": sub = (int)(3*Math.random()+18); break;
            case "CHRIS BROWN": sub = (int)(3*Math.random()+21); break;
            case "PARTYNEXTDOOR": sub = (int)(3*Math.random()+24); break;
            case "ALI GATIE": sub = (int)(3*Math.random()+27); break;
            default:
                break;
        }
        
        //Declare and initialize String array for genre subartists
        String [] rb = new String [30];
        
        //Assign values to String array for genre subartists
        rb [0] = "BAZZI";
        rb [1] = "BLACKBEAR";
        rb [2] = "VICTORIA MONET";
        rb [3] = "SABRINA CLAUDIO";
        rb [4] = "MAC AYRES";
        rb [5] = "OMAR APOLLO";
        rb [6] = "CHILDISH GAMBINO";
        rb [7] = "J COLE";
        rb [8] = "KID CUDI";
        rb [9] = "BROCKHAMPTON";
        rb [10] = "SZA";
        rb [11] = "TYLER, THE CREATOR";
        rb [12] = "KEHLANI";
        rb [13] = "JESSIE REYEZ";
        rb [14] = "ELLA MAI";
        rb [15] = "MEEK MILL";
        rb [16] = "JEREMIH";
        rb [17] = "FRENCH MONTANA";
        rb [18] = "MIGUEL";
        rb [19] = "H.E.R.";
        rb [20] = "SUMMER WALKER";
        rb [21] = "NE-YO";
        rb [22] = "USHER";
        rb [23] = "JAQUEES";
        rb [24] = "ROY WOODS";
        rb [25] = "BRYSON TILLER";
        rb [26] = "6LACK";
        rb [27] = "TATE MCRAE";
        rb [28] = "GNASH";
        rb [29] = "RUTH B";
        
        //Form output depending on randomly generated number
        switch (sub){
            case 0:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Bazzi.wav";
                ImageIcon codeBazzi = new ImageIcon("src\\codes\\bazzi.jpg");
                lblSubArtistCode.setIcon(codeBazzi);
                break;
            case 1:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Blackbear.wav";
                ImageIcon codeBlackbear = new ImageIcon("src\\codes\\blackbear.jpg");
                lblSubArtistCode.setIcon(codeBlackbear);
                break;
            case 2:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\VictoriaMonet.wav";
                ImageIcon codeVictoriaMonet = new ImageIcon("src\\codes\\monet.jpg");
                lblSubArtistCode.setIcon(codeVictoriaMonet);
                break;
                
            case 3:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\SabrinaClaudio.wav";
                ImageIcon codeSabrinaClaudio = new ImageIcon("src\\codes\\claudio.jpg");
                lblSubArtistCode.setIcon(codeSabrinaClaudio);
                break;  
            case 4:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\MacAyres.wav";
                ImageIcon codeMacAyres = new ImageIcon("src\\codes\\ayres.jpg");
                lblSubArtistCode.setIcon(codeMacAyres);
                break;     
            case 5:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\OmarApollo.wav";
                ImageIcon codeOmarApollo = new ImageIcon("src\\codes\\apollo.jpg");
                lblSubArtistCode.setIcon(codeOmarApollo);
                break;   
                
            case 6:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\ChildishGambino.wav";
                ImageIcon codeChildishGambino = new ImageIcon("src\\codes\\gambino.jpg");
                lblSubArtistCode.setIcon(codeChildishGambino);
                break;  
            case 7:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\JCole.wav";
                ImageIcon codeJCole = new ImageIcon("src\\codes\\jcole.jpg");
                lblSubArtistCode.setIcon(codeJCole);
                break;     
            case 8:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\KidCudi.wav";
                ImageIcon codeKidCudi = new ImageIcon("src\\codes\\cudi.jpg");
                lblSubArtistCode.setIcon(codeKidCudi);
                break;
                
            case 9:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\BROCKHAMPTON.wav";
                ImageIcon codeBROCKHAMPTON = new ImageIcon("src\\codes\\brockhampton.jpg");
                lblSubArtistCode.setIcon(codeBROCKHAMPTON);
                break;  
            case 10:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\SZA.wav";
                ImageIcon codeSZA = new ImageIcon("src\\codes\\sza.jpg");
                lblSubArtistCode.setIcon(codeSZA);
                break;     
            case 11:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Tyler_theCreator.wav";
                ImageIcon codeTyler_theCreator = new ImageIcon("src\\codes\\tyler.jpg");
                lblSubArtistCode.setIcon(codeTyler_theCreator);
                break;     
                
            case 12:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Kehlani.wav";
                ImageIcon codeKehlani = new ImageIcon("src\\codes\\kehlani.jpg");
                lblSubArtistCode.setIcon(codeKehlani);
                break;  
            case 13:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\JessieReyez.wav";
                ImageIcon codeJessieReyez = new ImageIcon("src\\codes\\reyez.jpg");
                lblSubArtistCode.setIcon(codeJessieReyez);
                break;     
            case 14:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\EllaMai.wav";
                ImageIcon codeEllaMai = new ImageIcon("src\\codes\\mai.jpg");
                lblSubArtistCode.setIcon(codeEllaMai);
                break;      
                
            case 15:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\MeekMill.wav";
                ImageIcon codeMeekMill = new ImageIcon("src\\codes\\meek.jpg");
                lblSubArtistCode.setIcon(codeMeekMill);
                break;  
            case 16:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Jeremih.wav";
                ImageIcon codeJeremih = new ImageIcon("src\\codes\\jeremih.jpg");
                lblSubArtistCode.setIcon(codeJeremih);
                break;     
            case 17:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\FrenchMontana.wav";
                ImageIcon codeFrenchMontana = new ImageIcon("src\\codes\\Fmontana.jpg");
                lblSubArtistCode.setIcon(codeFrenchMontana);
                break;      
                
            case 18:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Miguel.wav";
                ImageIcon codeMiguel = new ImageIcon("src\\codes\\miguel.jpg");
                lblSubArtistCode.setIcon(codeMiguel);
                break;  
            case 19:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\HER.wav";
                ImageIcon codeHER = new ImageIcon("src\\codes\\her.jpg");
                lblSubArtistCode.setIcon(codeHER);
                break;     
            case 20:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\SummerWalker.wav";
                ImageIcon codeSummerWalker = new ImageIcon("src\\codes\\walker.jpg");
                lblSubArtistCode.setIcon(codeSummerWalker);
                break;     
                
            case 21:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\NeYo.wav";
                ImageIcon codeNeYo = new ImageIcon("src\\codes\\neyo.jpg");
                lblSubArtistCode.setIcon(codeNeYo);
                break;  
            case 22:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Usher.wav";
                ImageIcon codeUsher = new ImageIcon("src\\codes\\usher.jpg");
                lblSubArtistCode.setIcon(codeUsher);
                break;     
            case 23:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Jacquees.wav";
                ImageIcon codeJaquees = new ImageIcon("src\\codes\\jaq.jpg");
                lblSubArtistCode.setIcon(codeJaquees);
                break;  
                
            case 24:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\RoyWoods.wav";
                ImageIcon codeRoyWoods = new ImageIcon("src\\codes\\woods.jpg");
                lblSubArtistCode.setIcon(codeRoyWoods);
                break;  
            case 25:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\BrysonTiller.wav";
                ImageIcon codeBrysonTiller = new ImageIcon("src\\codes\\tiller.jpg");
                lblSubArtistCode.setIcon(codeBrysonTiller);
                break;     
            case 26:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\6LACK.wav";
                ImageIcon code6LACK = new ImageIcon("src\\codes\\6LACK.jpg");
                lblSubArtistCode.setIcon(code6LACK);
                break;    
                
            case 27:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\TateMcRae.wav";
                ImageIcon codeTateMcRae = new ImageIcon("src\\codes\\mcrae.jpg");
                lblSubArtistCode.setIcon(codeTateMcRae);
                break;  
            case 28:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\Gnash.wav";
                ImageIcon codeGnash = new ImageIcon("src\\codes\\gnash.jpg");
                lblSubArtistCode.setIcon(codeGnash);
                break;     
            case 29:
                lblSubArtist.setText(rb[sub]);
                musicPath = "src\\Audios\\RuthB.wav";
                ImageIcon codeRuthB = new ImageIcon("src\\codes\\ruthB.jpg");
                lblSubArtistCode.setIcon(codeRuthB);
                break;        
            default:
                break;
        }
        
        //Make preference question not visible
        btnLikeYes.setVisible(false);
        btnNoLike.setVisible(false);
        lblDidYouLike.setVisible(false);
        lblPromptNextFrm.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnGenerateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateNewActionPerformed
        //Makes sub genre form visible again
        new FrmRBSub().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerateNewActionPerformed

    private void btnPlaySubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySubActionPerformed
        //Call playMusic method from main class
        playMusic(musicPath);
        
        //Make preference question visible
        btnLikeYes.setVisible(true);
        btnNoLike.setVisible(true);
        lblDidYouLike.setVisible(true);
    }//GEN-LAST:event_btnPlaySubActionPerformed

    private void btnBackToRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToRBActionPerformed
        //Makes R&B form visible
        new FrmRBForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToRBActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Makes Genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Makes Genres form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnNoLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoLikeActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Don't worry! There's lots more for you to find!");
    }//GEN-LAST:event_btnNoLikeActionPerformed

    private void btnLikeYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeYesActionPerformed
        //Makes message visible
        lblPromptNextFrm.setVisible(true);
        
        //Outputs appropriate message
        lblPromptNextFrm.setText("Great! Remember to scan their code on Spotify!");
    }//GEN-LAST:event_btnLikeYesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRBSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRBSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRBSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRBSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRBSub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackTo80s;
    private javax.swing.JButton btnBackTo80s1;
    private javax.swing.JButton btnBackTo80s2;
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToGenres1;
    private javax.swing.JButton btnBackToGenres2;
    private javax.swing.JButton btnBackToGenres3;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackToMenu1;
    private javax.swing.JButton btnBackToMenu2;
    private javax.swing.JButton btnBackToMenu3;
    private javax.swing.JButton btnBackToRB;
    private javax.swing.JButton btnGenerateNew;
    private javax.swing.JButton btnLikeYes;
    private javax.swing.JButton btnNoLike;
    private javax.swing.JButton btnPlaySong;
    private javax.swing.JButton btnPlaySong1;
    private javax.swing.JButton btnPlaySong2;
    private javax.swing.JButton btnPlaySub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblDidYouLike;
    private javax.swing.JLabel lblMainArtist;
    private javax.swing.JLabel lblMainArtistName;
    private javax.swing.JLabel lblMainArtistName1;
    private javax.swing.JLabel lblMainArtistName2;
    private javax.swing.JLabel lblPromptNextFrm;
    private javax.swing.JLabel lblSimilarCode;
    private javax.swing.JLabel lblSimilarCode1;
    private javax.swing.JLabel lblSimilarCode2;
    private javax.swing.JLabel lblSimilarName;
    private javax.swing.JLabel lblSimilarName1;
    private javax.swing.JLabel lblSimilarName2;
    private javax.swing.JLabel lblSubArtist;
    private javax.swing.JLabel lblSubArtistCode;
    // End of variables declaration//GEN-END:variables
}
