
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class Frm00sForm extends javax.swing.JFrame {
    
    //Declare public static String for main artists
    public static String thousandsSub;

    /**
     * Creates new form Frm00sForm
     */
    public Frm00sForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        btnBackToThrowbacks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnToPlainWhite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPlayPlainWhite = new javax.swing.JButton();
        btnCodePlainWhite = new javax.swing.JButton();
        btnToKeys = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPlayKeys = new javax.swing.JButton();
        btnCodKeys = new javax.swing.JButton();
        btnToBuble = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPlayBuble = new javax.swing.JButton();
        btnCodeBuble = new javax.swing.JButton();
        btnToCyrus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPlayCyrus = new javax.swing.JButton();
        btnCodeCyrus = new javax.swing.JButton();
        btnToRihanna = new javax.swing.JButton();
        btnCodeRihanna = new javax.swing.JButton();
        btnPlayRihanna = new javax.swing.JButton();
        btnToMars = new javax.swing.JButton();
        btnPlayMars = new javax.swing.JButton();
        btnCodeMars = new javax.swing.JButton();
        btnToColdplay = new javax.swing.JButton();
        btnPlayColdplay = new javax.swing.JButton();
        btnCodeColdplay = new javax.swing.JButton();
        btnToSpears = new javax.swing.JButton();
        btnPlaySpears = new javax.swing.JButton();
        btnCodeSpears = new javax.swing.JButton();
        btnToEminem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnPlayEminem = new javax.swing.JButton();
        btnCodeEminem = new javax.swing.JButton();
        btnToPink = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnPlayPink = new javax.swing.JButton();
        btnCodePink = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        jPanel2.setBackground(new java.awt.Color(255, 115, 185));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        btnBackToThrowbacks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToThrowbacks.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToThrowbacks.setText("DECADES");
        btnBackToThrowbacks.setContentAreaFilled(false);
        btnBackToThrowbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToThrowbacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnBackToThrowbacks)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addGap(18, 18, 18)
                .addComponent(btnBackToThrowbacks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("00s");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose your favourite artist from this genre.");

        btnToPlainWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/plainwhite.jpg"))); // NOI18N
        btnToPlainWhite.setContentAreaFilled(false);
        btnToPlainWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToPlainWhiteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLAIN WHITE T'S");

        btnPlayPlainWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayPlainWhite.setContentAreaFilled(false);
        btnPlayPlainWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPlainWhiteActionPerformed(evt);
            }
        });

        btnCodePlainWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodePlainWhite.setContentAreaFilled(false);
        btnCodePlainWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodePlainWhiteActionPerformed(evt);
            }
        });

        btnToKeys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/keys.jpg"))); // NOI18N
        btnToKeys.setContentAreaFilled(false);
        btnToKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToKeysActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ALICIA KEYS");

        btnPlayKeys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayKeys.setContentAreaFilled(false);
        btnPlayKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayKeysActionPerformed(evt);
            }
        });

        btnCodKeys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodKeys.setContentAreaFilled(false);
        btnCodKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodKeysActionPerformed(evt);
            }
        });

        btnToBuble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/buble.jpg"))); // NOI18N
        btnToBuble.setContentAreaFilled(false);
        btnToBuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBubleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MICHAEL BUBLE");

        btnPlayBuble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayBuble.setContentAreaFilled(false);
        btnPlayBuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBubleActionPerformed(evt);
            }
        });

        btnCodeBuble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeBuble.setContentAreaFilled(false);
        btnCodeBuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeBubleActionPerformed(evt);
            }
        });

        btnToCyrus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/cyrus.png"))); // NOI18N
        btnToCyrus.setContentAreaFilled(false);
        btnToCyrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToCyrusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MILEY CYRUS");

        btnPlayCyrus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayCyrus.setContentAreaFilled(false);
        btnPlayCyrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayCyrusActionPerformed(evt);
            }
        });

        btnCodeCyrus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeCyrus.setContentAreaFilled(false);
        btnCodeCyrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeCyrusActionPerformed(evt);
            }
        });

        btnToRihanna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/rihanna.jpg"))); // NOI18N
        btnToRihanna.setContentAreaFilled(false);
        btnToRihanna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToRihannaActionPerformed(evt);
            }
        });

        btnCodeRihanna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeRihanna.setContentAreaFilled(false);
        btnCodeRihanna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeRihannaActionPerformed(evt);
            }
        });

        btnPlayRihanna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayRihanna.setContentAreaFilled(false);
        btnPlayRihanna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayRihannaActionPerformed(evt);
            }
        });

        btnToMars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/mars.jpg"))); // NOI18N
        btnToMars.setContentAreaFilled(false);
        btnToMars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMarsActionPerformed(evt);
            }
        });

        btnPlayMars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMars.setContentAreaFilled(false);
        btnPlayMars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMarsActionPerformed(evt);
            }
        });

        btnCodeMars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMars.setContentAreaFilled(false);
        btnCodeMars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMarsActionPerformed(evt);
            }
        });

        btnToColdplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/coldplay.jpg"))); // NOI18N
        btnToColdplay.setContentAreaFilled(false);
        btnToColdplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToColdplayActionPerformed(evt);
            }
        });

        btnPlayColdplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayColdplay.setContentAreaFilled(false);
        btnPlayColdplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayColdplayActionPerformed(evt);
            }
        });

        btnCodeColdplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeColdplay.setContentAreaFilled(false);
        btnCodeColdplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeColdplayActionPerformed(evt);
            }
        });

        btnToSpears.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/spears.jpg"))); // NOI18N
        btnToSpears.setContentAreaFilled(false);
        btnToSpears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToSpearsActionPerformed(evt);
            }
        });

        btnPlaySpears.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlaySpears.setContentAreaFilled(false);
        btnPlaySpears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySpearsActionPerformed(evt);
            }
        });

        btnCodeSpears.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeSpears.setContentAreaFilled(false);
        btnCodeSpears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeSpearsActionPerformed(evt);
            }
        });

        btnToEminem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/em.jpeg"))); // NOI18N
        btnToEminem.setContentAreaFilled(false);
        btnToEminem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEminemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMINEM");

        btnPlayEminem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayEminem.setContentAreaFilled(false);
        btnPlayEminem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayEminemActionPerformed(evt);
            }
        });

        btnCodeEminem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeEminem.setContentAreaFilled(false);
        btnCodeEminem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeEminemActionPerformed(evt);
            }
        });

        btnToPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/thousands/pink.jpg"))); // NOI18N
        btnToPink.setContentAreaFilled(false);
        btnToPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToPinkActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("P!NK");

        btnPlayPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayPink.setContentAreaFilled(false);
        btnPlayPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPinkActionPerformed(evt);
            }
        });

        btnCodePink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodePink.setContentAreaFilled(false);
        btnCodePink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodePinkActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RIHANNA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BRUNO MARS");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COLDPLAY");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BRITNEY SPEARS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToPlainWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel5)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel6))
                            .addComponent(btnPlayPlainWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCodePlainWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnToEminem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnCodeEminem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPlayEminem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnToPink, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabel12))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToRihanna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayRihanna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeRihanna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnToKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnToMars, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeMars, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayMars, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodePink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayPink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(btnToColdplay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnToBuble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel9)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCodeColdplay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayColdplay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCodeBuble, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayBuble, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnToSpears, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToCyrus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCodeSpears, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaySpears, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCodeCyrus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayCyrus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel11)))))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnToPlainWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGap(1, 1, 1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnCodePlainWhite)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPlayPlainWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToCyrus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCodeCyrus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayCyrus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(btnCodeBuble)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPlayBuble, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnToKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnToBuble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnCodKeys)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPlayKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(73, 73, 73)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCodeSpears)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaySpears, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCodeRihanna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayRihanna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCodeMars)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlayMars, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCodeColdplay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlayColdplay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnToRihanna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnToMars, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnToColdplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToSpears, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCodeEminem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayEminem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnToPink, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToEminem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCodePink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayPink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToPlainWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToPlainWhiteActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "PLAIN WHITE T'S";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToPlainWhiteActionPerformed

    private void btnPlayPlainWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPlainWhiteActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\PlainWhiteTs.wav");
    }//GEN-LAST:event_btnPlayPlainWhiteActionPerformed

    private void btnCodePlainWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodePlainWhiteActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\plainWhite.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodePlainWhiteActionPerformed

    private void btnToKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToKeysActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "ALICIA KEYS";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToKeysActionPerformed

    private void btnPlayKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayKeysActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\AliciaKeys.wav");
    }//GEN-LAST:event_btnPlayKeysActionPerformed

    private void btnCodKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodKeysActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\keys.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodKeysActionPerformed

    private void btnPlayBubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBubleActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\MichaelBuble.wav");
    }//GEN-LAST:event_btnPlayBubleActionPerformed

    private void btnCodeBubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeBubleActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\buble.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeBubleActionPerformed

    private void btnPlayCyrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayCyrusActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\MileyCyrus.wav");
    }//GEN-LAST:event_btnPlayCyrusActionPerformed

    private void btnCodeCyrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeCyrusActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\cyrus.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeCyrusActionPerformed

    private void btnCodeRihannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeRihannaActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\rihanna.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeRihannaActionPerformed

    private void btnPlayRihannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayRihannaActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Rihanna.wav");
    }//GEN-LAST:event_btnPlayRihannaActionPerformed

    private void btnPlayMarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMarsActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\BrunoMars.wav");
    }//GEN-LAST:event_btnPlayMarsActionPerformed

    private void btnCodeMarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMarsActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\mars.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMarsActionPerformed

    private void btnPlayColdplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayColdplayActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Coldplay.wav");
    }//GEN-LAST:event_btnPlayColdplayActionPerformed

    private void btnCodeColdplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeColdplayActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\coldplay.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeColdplayActionPerformed

    private void btnPlaySpearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySpearsActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\BritneySpears.wav");
    }//GEN-LAST:event_btnPlaySpearsActionPerformed

    private void btnCodeSpearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeSpearsActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\spears.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeSpearsActionPerformed

    private void btnPlayEminemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayEminemActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Eminem.wav");
    }//GEN-LAST:event_btnPlayEminemActionPerformed

    private void btnCodeEminemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeEminemActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\eminem.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeEminemActionPerformed

    private void btnPlayPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPinkActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Pink.wav");
    }//GEN-LAST:event_btnPlayPinkActionPerformed

    private void btnCodePinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodePinkActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\pink.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodePinkActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Makes menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Makes genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnToBubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBubleActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "MICHAEL BUBLE";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToBubleActionPerformed

    private void btnToCyrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToCyrusActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "MILEY CYRUS";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToCyrusActionPerformed

    private void btnToRihannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToRihannaActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "RIHANNA";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToRihannaActionPerformed

    private void btnToMarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMarsActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "BRUNO MARS";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMarsActionPerformed

    private void btnToColdplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToColdplayActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "COLDPLAY";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToColdplayActionPerformed

    private void btnToSpearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToSpearsActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "BRITNEY SPEARS";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToSpearsActionPerformed

    private void btnToEminemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEminemActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "EMINEM";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToEminemActionPerformed

    private void btnToPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToPinkActionPerformed
        //Assign main artist name to public variable
        thousandsSub = "P!NK";
        
        //Make sub genre form visible
        new Frm00sSub(thousandsSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToPinkActionPerformed

    private void btnBackToThrowbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToThrowbacksActionPerformed
        //Make Throwbacks form visible
        new FrmThrowbacksForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToThrowbacksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm00sForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm00sForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm00sForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm00sForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm00sForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackToThrowbacks;
    private javax.swing.JButton btnCodKeys;
    private javax.swing.JButton btnCodeBuble;
    private javax.swing.JButton btnCodeColdplay;
    private javax.swing.JButton btnCodeCyrus;
    private javax.swing.JButton btnCodeEminem;
    private javax.swing.JButton btnCodeMars;
    private javax.swing.JButton btnCodePink;
    private javax.swing.JButton btnCodePlainWhite;
    private javax.swing.JButton btnCodeRihanna;
    private javax.swing.JButton btnCodeSpears;
    private javax.swing.JButton btnPlayBuble;
    private javax.swing.JButton btnPlayColdplay;
    private javax.swing.JButton btnPlayCyrus;
    private javax.swing.JButton btnPlayEminem;
    private javax.swing.JButton btnPlayKeys;
    private javax.swing.JButton btnPlayMars;
    private javax.swing.JButton btnPlayPink;
    private javax.swing.JButton btnPlayPlainWhite;
    private javax.swing.JButton btnPlayRihanna;
    private javax.swing.JButton btnPlaySpears;
    private javax.swing.JButton btnToBuble;
    private javax.swing.JButton btnToColdplay;
    private javax.swing.JButton btnToCyrus;
    private javax.swing.JButton btnToEminem;
    private javax.swing.JButton btnToKeys;
    private javax.swing.JButton btnToMars;
    private javax.swing.JButton btnToPink;
    private javax.swing.JButton btnToPlainWhite;
    private javax.swing.JButton btnToRihanna;
    private javax.swing.JButton btnToSpears;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
