
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class FrmClassicalForm extends javax.swing.JFrame {

    //Declare public static String for main artists
    public static String classSub;
    
    /**
     * Creates new form FrmClassicalForm
     */
    public FrmClassicalForm() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnToBach = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCodeBach = new javax.swing.JButton();
        btnPlayBach = new javax.swing.JButton();
        btnToMozart = new javax.swing.JButton();
        btnCodeMozart = new javax.swing.JButton();
        btnPlayMozart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnToBeethoven = new javax.swing.JButton();
        btnCodeBeethoven = new javax.swing.JButton();
        btnPlayBeethoven = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnToWagner = new javax.swing.JButton();
        btnCodeWagner = new javax.swing.JButton();
        btnPlayWagner = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnToBrahms = new javax.swing.JButton();
        btnCodeBrahms = new javax.swing.JButton();
        btnPlayBrahms = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnToSchuann = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPlaySchuann = new javax.swing.JButton();
        btnCodeSchuann = new javax.swing.JButton();
        btnToWilliams = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCodeWilliams = new javax.swing.JButton();
        btnPlayWilliams = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCodeMahler = new javax.swing.JButton();
        btnPlayMahler = new javax.swing.JButton();
        btnToHaydn = new javax.swing.JButton();
        btnCodeHaydn = new javax.swing.JButton();
        btnPlayHaydn = new javax.swing.JButton();
        btnToGiacchino = new javax.swing.JButton();
        btnCodeGiacchino = new javax.swing.JButton();
        btnPlayGiacchino = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnToMahler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLASSICAL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose your favourite artist from this genre.");

        btnToBach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Bach.jpg"))); // NOI18N
        btnToBach.setContentAreaFilled(false);
        btnToBach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBachActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JOHANN SEBASTIAN BACH");

        btnCodeBach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeBach.setContentAreaFilled(false);
        btnCodeBach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeBachActionPerformed(evt);
            }
        });

        btnPlayBach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayBach.setContentAreaFilled(false);
        btnPlayBach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBachActionPerformed(evt);
            }
        });

        btnToMozart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Mozart.jpg"))); // NOI18N
        btnToMozart.setContentAreaFilled(false);
        btnToMozart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMozartActionPerformed(evt);
            }
        });

        btnCodeMozart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMozart.setContentAreaFilled(false);
        btnCodeMozart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMozartActionPerformed(evt);
            }
        });

        btnPlayMozart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMozart.setContentAreaFilled(false);
        btnPlayMozart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMozartActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WOLFGANG AMADEUS MOZART");

        btnToBeethoven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Beethoven.jpg"))); // NOI18N
        btnToBeethoven.setContentAreaFilled(false);
        btnToBeethoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBeethovenActionPerformed(evt);
            }
        });

        btnCodeBeethoven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeBeethoven.setContentAreaFilled(false);
        btnCodeBeethoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeBeethovenActionPerformed(evt);
            }
        });

        btnPlayBeethoven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayBeethoven.setContentAreaFilled(false);
        btnPlayBeethoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBeethovenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUDWIG VAN BEETHOVEN");

        btnToWagner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Wagner.jpg"))); // NOI18N
        btnToWagner.setContentAreaFilled(false);
        btnToWagner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToWagnerActionPerformed(evt);
            }
        });

        btnCodeWagner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeWagner.setContentAreaFilled(false);
        btnCodeWagner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeWagnerActionPerformed(evt);
            }
        });

        btnPlayWagner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayWagner.setContentAreaFilled(false);
        btnPlayWagner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayWagnerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RICHARD WAGNER");

        btnToBrahms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Brahms.jpg"))); // NOI18N
        btnToBrahms.setContentAreaFilled(false);
        btnToBrahms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBrahmsActionPerformed(evt);
            }
        });

        btnCodeBrahms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeBrahms.setContentAreaFilled(false);
        btnCodeBrahms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeBrahmsActionPerformed(evt);
            }
        });

        btnPlayBrahms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayBrahms.setContentAreaFilled(false);
        btnPlayBrahms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBrahmsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ROBERT SCHUANN");

        btnToSchuann.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Schumann.jpg"))); // NOI18N
        btnToSchuann.setContentAreaFilled(false);
        btnToSchuann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToSchuannActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JOHANNES BRAHMS");

        btnPlaySchuann.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlaySchuann.setContentAreaFilled(false);
        btnPlaySchuann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySchuannActionPerformed(evt);
            }
        });

        btnCodeSchuann.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeSchuann.setContentAreaFilled(false);
        btnCodeSchuann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeSchuannActionPerformed(evt);
            }
        });

        btnToWilliams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Williams.jpg"))); // NOI18N
        btnToWilliams.setContentAreaFilled(false);
        btnToWilliams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToWilliamsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RALPH VAUGHN WILLIAMS");

        btnCodeWilliams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeWilliams.setContentAreaFilled(false);
        btnCodeWilliams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeWilliamsActionPerformed(evt);
            }
        });

        btnPlayWilliams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayWilliams.setContentAreaFilled(false);
        btnPlayWilliams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayWilliamsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GUSTAV MAHLER");

        btnCodeMahler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMahler.setContentAreaFilled(false);
        btnCodeMahler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMahlerActionPerformed(evt);
            }
        });

        btnPlayMahler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMahler.setContentAreaFilled(false);
        btnPlayMahler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMahlerActionPerformed(evt);
            }
        });

        btnToHaydn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Haydn.jpg"))); // NOI18N
        btnToHaydn.setContentAreaFilled(false);
        btnToHaydn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHaydnActionPerformed(evt);
            }
        });

        btnCodeHaydn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeHaydn.setContentAreaFilled(false);
        btnCodeHaydn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeHaydnActionPerformed(evt);
            }
        });

        btnPlayHaydn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayHaydn.setContentAreaFilled(false);
        btnPlayHaydn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayHaydnActionPerformed(evt);
            }
        });

        btnToGiacchino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Giacchino.jpg"))); // NOI18N
        btnToGiacchino.setContentAreaFilled(false);
        btnToGiacchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToGiacchinoActionPerformed(evt);
            }
        });

        btnCodeGiacchino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeGiacchino.setContentAreaFilled(false);
        btnCodeGiacchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeGiacchinoActionPerformed(evt);
            }
        });

        btnPlayGiacchino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayGiacchino.setContentAreaFilled(false);
        btnPlayGiacchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGiacchinoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MICHAEL GIACCHINO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FRANZ JOSEPH HAYDN");

        btnToMahler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/classical/Mahler.jpg"))); // NOI18N
        btnToMahler.setContentAreaFilled(false);
        btnToMahler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMahlerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayMozart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeMozart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(177, 177, 177)
                                        .addComponent(jLabel4)))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToBeethoven, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeBeethoven, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayBeethoven, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(btnToWagner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeWagner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayWagner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel7)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnToBrahms, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnPlayBrahms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnCodeBrahms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnToSchuann, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnToHaydn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnCodeHaydn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnPlayHaydn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel8)))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel12))
                                                    .addComponent(btnToGiacchino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeSchuann, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlaySchuann, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeGiacchino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayGiacchino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(btnToWilliams, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeWilliams, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayWilliams, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(btnToMahler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeMahler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayMahler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel11))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnToBach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlayBach, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCodeBach, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnToMozart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToBach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnToMozart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnCodeBach)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlayBach, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnToBeethoven, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnToWagner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCodeWagner)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPlayWagner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnCodeBeethoven))
                                    .addComponent(btnCodeMozart, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPlayMozart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayBeethoven, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCodeMahler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayMahler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCodeBrahms)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayBrahms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCodeSchuann)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlaySchuann, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCodeWilliams)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPlayWilliams, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnToBrahms, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnToSchuann, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnToWilliams, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToMahler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCodeHaydn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayHaydn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnToGiacchino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToHaydn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCodeGiacchino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayGiacchino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Makes menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Makes genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnToBachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBachActionPerformed
        //Assign main artist name to public variable
        classSub = "JOHANN SEBASTIAN BACH";
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToBachActionPerformed

    private void btnCodeBachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeBachActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\JohannSebastianBach.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeBachActionPerformed

    private void btnPlayBachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBachActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\JohannSebastianBach.wav");
    }//GEN-LAST:event_btnPlayBachActionPerformed

    private void btnToMozartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMozartActionPerformed
        //Assign main artist name to public variable
        classSub = "WOLFGANG AMADES MOZART";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMozartActionPerformed

    private void btnCodeMozartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMozartActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\WolfgangAmadeusMozart.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMozartActionPerformed

    private void btnPlayMozartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMozartActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\WolfgangAmadeusMozart.wav");
    }//GEN-LAST:event_btnPlayMozartActionPerformed

    private void btnCodeBeethovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeBeethovenActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\LudwigVanBeethoven.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeBeethovenActionPerformed

    private void btnPlayBeethovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBeethovenActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\LudwigVanBeethoven.wav");
    }//GEN-LAST:event_btnPlayBeethovenActionPerformed

    private void btnCodeWagnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeWagnerActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\RichardWagner.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeWagnerActionPerformed

    private void btnPlayWagnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayWagnerActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\RichardWagner.wav");
    }//GEN-LAST:event_btnPlayWagnerActionPerformed

    private void btnCodeBrahmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeBrahmsActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\JohannesBrahms.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeBrahmsActionPerformed

    private void btnPlayBrahmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBrahmsActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\JohannesBrahms.wav");
    }//GEN-LAST:event_btnPlayBrahmsActionPerformed

    private void btnPlaySchuannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySchuannActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\RobertSchumann.wav");
    }//GEN-LAST:event_btnPlaySchuannActionPerformed

    private void btnCodeSchuannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeSchuannActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\RobertSchumann.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeSchuannActionPerformed

    private void btnCodeWilliamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeWilliamsActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\RalphVaughnWilliams.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeWilliamsActionPerformed

    private void btnPlayWilliamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayWilliamsActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\RalphVaughnWilliams.wav");
    }//GEN-LAST:event_btnPlayWilliamsActionPerformed

    private void btnCodeMahlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMahlerActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\GustavMahler.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMahlerActionPerformed

    private void btnPlayMahlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMahlerActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\GustavMahler.wav");
    }//GEN-LAST:event_btnPlayMahlerActionPerformed

    private void btnCodeHaydnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeHaydnActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\FranzJosephHaydn.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeHaydnActionPerformed

    private void btnPlayHaydnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayHaydnActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\FranzJosephHaydn.wav");
    }//GEN-LAST:event_btnPlayHaydnActionPerformed

    private void btnCodeGiacchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeGiacchinoActionPerformed
        ImageIcon code = new ImageIcon("src\\codes\\MichaelGiacchino.jpg");
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeGiacchinoActionPerformed

    private void btnPlayGiacchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayGiacchinoActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\MichaelGiacchino.wav");
    }//GEN-LAST:event_btnPlayGiacchinoActionPerformed

    private void btnToBeethovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBeethovenActionPerformed
        //Assign main artist name to public variable
        classSub = "LUDWIG VAN BEETHOVEN";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToBeethovenActionPerformed

    private void btnToWagnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToWagnerActionPerformed
        //Assign main artist name to public variable
        classSub = "RICHARD WAGNER";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToWagnerActionPerformed

    private void btnToBrahmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBrahmsActionPerformed
        //Assign main artist name to public variable
        classSub = "JOHANNES BRAHMS";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToBrahmsActionPerformed

    private void btnToSchuannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToSchuannActionPerformed
        //Assign main artist name to public variable
        classSub = "ROBERT SCHUMANN";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToSchuannActionPerformed

    private void btnToWilliamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToWilliamsActionPerformed
        //Assign main artist name to public variable
        classSub = "RALPH VAUGHN WILLIAMS";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToWilliamsActionPerformed

    private void btnToMahlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMahlerActionPerformed
        //Assign main artist name to public variable
        classSub = "GUSTAV MAHLER";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMahlerActionPerformed

    private void btnToHaydnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHaydnActionPerformed
        //Assign main artist name to public variable
        classSub = "FRANZ JOSEPH HAYDEN";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToHaydnActionPerformed

    private void btnToGiacchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToGiacchinoActionPerformed
        //Assign main artist name to public variable
        classSub = "MICHEAL GIACCHINO";
        
        //Make sub genre form visible
        new FrmClassicalSub(classSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToGiacchinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClassicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClassicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClassicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClassicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClassicalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnCodeBach;
    private javax.swing.JButton btnCodeBeethoven;
    private javax.swing.JButton btnCodeBrahms;
    private javax.swing.JButton btnCodeGiacchino;
    private javax.swing.JButton btnCodeHaydn;
    private javax.swing.JButton btnCodeMahler;
    private javax.swing.JButton btnCodeMozart;
    private javax.swing.JButton btnCodeSchuann;
    private javax.swing.JButton btnCodeWagner;
    private javax.swing.JButton btnCodeWilliams;
    private javax.swing.JButton btnPlayBach;
    private javax.swing.JButton btnPlayBeethoven;
    private javax.swing.JButton btnPlayBrahms;
    private javax.swing.JButton btnPlayGiacchino;
    private javax.swing.JButton btnPlayHaydn;
    private javax.swing.JButton btnPlayMahler;
    private javax.swing.JButton btnPlayMozart;
    private javax.swing.JButton btnPlaySchuann;
    private javax.swing.JButton btnPlayWagner;
    private javax.swing.JButton btnPlayWilliams;
    private javax.swing.JButton btnToBach;
    private javax.swing.JButton btnToBeethoven;
    private javax.swing.JButton btnToBrahms;
    private javax.swing.JButton btnToGiacchino;
    private javax.swing.JButton btnToHaydn;
    private javax.swing.JButton btnToMahler;
    private javax.swing.JButton btnToMozart;
    private javax.swing.JButton btnToSchuann;
    private javax.swing.JButton btnToWagner;
    private javax.swing.JButton btnToWilliams;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
