
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class FrmJazzForm extends javax.swing.JFrame {
    
    //Declare public static String for main artists
    public static String jazzSub;

    /**
     * Creates new form FrmJazzForm
     */
    public FrmJazzForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnToColtrane = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPlayColtrane = new javax.swing.JButton();
        btnCodeColtrane = new javax.swing.JButton();
        btnToDavis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPlayDavis = new javax.swing.JButton();
        btnCodeDavis = new javax.swing.JButton();
        btnToArmstrong = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPlayArmstrong = new javax.swing.JButton();
        btnCodeArmstrong = new javax.swing.JButton();
        btnToHancock = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPlayHancock = new javax.swing.JButton();
        btnCodeHancock = new javax.swing.JButton();
        btnToEllington = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnPlayEllington = new javax.swing.JButton();
        btnCodeEllington = new javax.swing.JButton();
        btnToParker = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPlayParker = new javax.swing.JButton();
        btnCodeParker = new javax.swing.JButton();
        btnToHoliday = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPlayHoliday = new javax.swing.JButton();
        btnCodeHoliday = new javax.swing.JButton();
        btnToMonk = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnPlayMonk = new javax.swing.JButton();
        btnCodeMonk = new javax.swing.JButton();
        btnToMason = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnPlayMason = new javax.swing.JButton();
        btnCodeMason = new javax.swing.JButton();
        btnToEvans = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnPlayEvans = new javax.swing.JButton();
        btnCodeEvans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 218, 113));

        jPanel2.setBackground(new java.awt.Color(205, 205, 71));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JAZZ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose your favourite artist from this genre.");

        btnToColtrane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/coltrane.jpg"))); // NOI18N
        btnToColtrane.setContentAreaFilled(false);
        btnToColtrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToColtraneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JOHN COLTRANE");

        btnPlayColtrane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayColtrane.setContentAreaFilled(false);
        btnPlayColtrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayColtraneActionPerformed(evt);
            }
        });

        btnCodeColtrane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeColtrane.setContentAreaFilled(false);
        btnCodeColtrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeColtraneActionPerformed(evt);
            }
        });

        btnToDavis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/davis.jpg"))); // NOI18N
        btnToDavis.setContentAreaFilled(false);
        btnToDavis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToDavisActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MILES DAVIS");

        btnPlayDavis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayDavis.setContentAreaFilled(false);
        btnPlayDavis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayDavisActionPerformed(evt);
            }
        });

        btnCodeDavis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeDavis.setContentAreaFilled(false);
        btnCodeDavis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeDavisActionPerformed(evt);
            }
        });

        btnToArmstrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/armstrong.jpg"))); // NOI18N
        btnToArmstrong.setContentAreaFilled(false);
        btnToArmstrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToArmstrongActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOUIS ARMSTRONG");

        btnPlayArmstrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayArmstrong.setContentAreaFilled(false);
        btnPlayArmstrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayArmstrongActionPerformed(evt);
            }
        });

        btnCodeArmstrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeArmstrong.setContentAreaFilled(false);
        btnCodeArmstrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeArmstrongActionPerformed(evt);
            }
        });

        btnToHancock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/hancock.JPG"))); // NOI18N
        btnToHancock.setContentAreaFilled(false);
        btnToHancock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHancockActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HERBIE HANCOCK");

        btnPlayHancock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayHancock.setContentAreaFilled(false);
        btnPlayHancock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayHancockActionPerformed(evt);
            }
        });

        btnCodeHancock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeHancock.setContentAreaFilled(false);
        btnCodeHancock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeHancockActionPerformed(evt);
            }
        });

        btnToEllington.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/duke.jpg"))); // NOI18N
        btnToEllington.setContentAreaFilled(false);
        btnToEllington.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEllingtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DUKE ELLINGTON");

        btnPlayEllington.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayEllington.setContentAreaFilled(false);
        btnPlayEllington.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayEllingtonActionPerformed(evt);
            }
        });

        btnCodeEllington.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeEllington.setContentAreaFilled(false);
        btnCodeEllington.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeEllingtonActionPerformed(evt);
            }
        });

        btnToParker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/parker1.jpg"))); // NOI18N
        btnToParker.setContentAreaFilled(false);
        btnToParker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToParkerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CHARLIE PARKER");

        btnPlayParker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayParker.setContentAreaFilled(false);
        btnPlayParker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayParkerActionPerformed(evt);
            }
        });

        btnCodeParker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeParker.setContentAreaFilled(false);
        btnCodeParker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeParkerActionPerformed(evt);
            }
        });

        btnToHoliday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/holiday.jpg"))); // NOI18N
        btnToHoliday.setContentAreaFilled(false);
        btnToHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHolidayActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BILLE HOLIDAY");

        btnPlayHoliday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayHoliday.setContentAreaFilled(false);
        btnPlayHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayHolidayActionPerformed(evt);
            }
        });

        btnCodeHoliday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeHoliday.setContentAreaFilled(false);
        btnCodeHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeHolidayActionPerformed(evt);
            }
        });

        btnToMonk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/thelonious.jpg"))); // NOI18N
        btnToMonk.setContentAreaFilled(false);
        btnToMonk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMonkActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("THELONIOUS MONK");

        btnPlayMonk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMonk.setContentAreaFilled(false);
        btnPlayMonk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMonkActionPerformed(evt);
            }
        });

        btnCodeMonk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMonk.setContentAreaFilled(false);
        btnCodeMonk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMonkActionPerformed(evt);
            }
        });

        btnToMason.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/mason.jpg"))); // NOI18N
        btnToMason.setContentAreaFilled(false);
        btnToMason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMasonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JAMES MASON");

        btnPlayMason.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMason.setContentAreaFilled(false);
        btnPlayMason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMasonActionPerformed(evt);
            }
        });

        btnCodeMason.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMason.setContentAreaFilled(false);
        btnCodeMason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMasonActionPerformed(evt);
            }
        });

        btnToEvans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/jazz/evans.jpg"))); // NOI18N
        btnToEvans.setContentAreaFilled(false);
        btnToEvans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEvansActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BILL EVANS");

        btnPlayEvans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayEvans.setContentAreaFilled(false);
        btnPlayEvans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayEvansActionPerformed(evt);
            }
        });

        btnCodeEvans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeEvans.setContentAreaFilled(false);
        btnCodeEvans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeEvansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToMason, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCodeMason, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayMason, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnToEvans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToColtrane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPlayColtrane, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeColtrane, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToEllington, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeEllington, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayEllington, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnToParker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnToDavis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(42, 42, 42)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeEvans, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayEvans, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayDavis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeDavis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeParker, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayParker, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnToMonk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToArmstrong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeArmstrong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayArmstrong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(btnToHancock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCodeHancock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayHancock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCodeMonk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayMonk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel11)))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCodeColtrane)
                            .addComponent(btnCodeDavis)
                            .addComponent(btnCodeArmstrong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlayColtrane, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlayDavis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlayArmstrong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnToDavis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToColtrane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToArmstrong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToHancock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCodeHancock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayHancock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnToParker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnToEllington, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(btnCodeHoliday)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPlayHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnCodeParker)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayParker, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnToEvans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToMason, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCodeEvans)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayEvans, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToMonk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnCodeEllington)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayEllington, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnCodeMonk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlayMonk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCodeMason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayMason, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Makes menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Makes genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnToColtraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToColtraneActionPerformed
        //Assign main artist name to public variable
        jazzSub = "JOHN COLTRANE";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToColtraneActionPerformed

    private void btnPlayColtraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayColtraneActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\JohnColtrane.wav");
    }//GEN-LAST:event_btnPlayColtraneActionPerformed

    private void btnCodeColtraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeColtraneActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\coltrane.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeColtraneActionPerformed

    private void btnToDavisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToDavisActionPerformed
        //Assign main artist name to public variable
        jazzSub = "MILES DAVIS";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToDavisActionPerformed

    private void btnPlayDavisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayDavisActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\MilesDavis.wav");
    }//GEN-LAST:event_btnPlayDavisActionPerformed

    private void btnCodeDavisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeDavisActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\davis.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeDavisActionPerformed

    private void btnPlayArmstrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayArmstrongActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\LouisArmstrong.wav");
    }//GEN-LAST:event_btnPlayArmstrongActionPerformed

    private void btnCodeArmstrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeArmstrongActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\armstrong.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeArmstrongActionPerformed

    private void btnPlayHancockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayHancockActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\HerbieHancock.wav");
    }//GEN-LAST:event_btnPlayHancockActionPerformed

    private void btnCodeHancockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeHancockActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\hancock.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeHancockActionPerformed

    private void btnPlayEllingtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayEllingtonActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\DukeEllington.wav");
    }//GEN-LAST:event_btnPlayEllingtonActionPerformed

    private void btnCodeEllingtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeEllingtonActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\ellington.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeEllingtonActionPerformed

    private void btnPlayParkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayParkerActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\CharlieParker.wav");
    }//GEN-LAST:event_btnPlayParkerActionPerformed

    private void btnCodeParkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeParkerActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\parker.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeParkerActionPerformed

    private void btnPlayHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayHolidayActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\BillieHoliday.wav");
    }//GEN-LAST:event_btnPlayHolidayActionPerformed

    private void btnCodeHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeHolidayActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\holiday.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeHolidayActionPerformed

    private void btnPlayMonkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMonkActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\TheloniousMonk.wav");
    }//GEN-LAST:event_btnPlayMonkActionPerformed

    private void btnCodeMonkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMonkActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\monk.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMonkActionPerformed

    private void btnPlayMasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMasonActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\JamesMason.wav");
    }//GEN-LAST:event_btnPlayMasonActionPerformed

    private void btnCodeMasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMasonActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\mason.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMasonActionPerformed

    private void btnPlayEvansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayEvansActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\BillEvans.wav");
    }//GEN-LAST:event_btnPlayEvansActionPerformed

    private void btnCodeEvansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeEvansActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\evans.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeEvansActionPerformed

    private void btnToArmstrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToArmstrongActionPerformed
        //Assign main artist name to public variable
        jazzSub = "LOUIS ARMSTRONG";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToArmstrongActionPerformed

    private void btnToHancockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHancockActionPerformed
        //Assign main artist name to public variable
        jazzSub = "HERBIE HANCOCK";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToHancockActionPerformed

    private void btnToEllingtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEllingtonActionPerformed
        //Assign main artist name to public variable
        jazzSub = "DUKE ELLINGTON";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToEllingtonActionPerformed

    private void btnToParkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToParkerActionPerformed
        //Assign main artist name to public variable
        jazzSub = "CHARLIE PARKER";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToParkerActionPerformed

    private void btnToHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHolidayActionPerformed
        //Assign main artist name to public variable
        jazzSub = "BILLIE HOLIDAY";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToHolidayActionPerformed

    private void btnToMonkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMonkActionPerformed
        //Assign main artist name to public variable
        jazzSub = "THELONIOUS MONK";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMonkActionPerformed

    private void btnToMasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMasonActionPerformed
        //Assign main artist name to public variable
        jazzSub = "JAMES MASON";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMasonActionPerformed

    private void btnToEvansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEvansActionPerformed
        //Assign main artist name to public variable
        jazzSub = "BILL EVANS";
        
        //Make sub genre form visible
        new FrmJazzSub(jazzSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToEvansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJazzForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJazzForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJazzForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJazzForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJazzForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnCodeArmstrong;
    private javax.swing.JButton btnCodeColtrane;
    private javax.swing.JButton btnCodeDavis;
    private javax.swing.JButton btnCodeEllington;
    private javax.swing.JButton btnCodeEvans;
    private javax.swing.JButton btnCodeHancock;
    private javax.swing.JButton btnCodeHoliday;
    private javax.swing.JButton btnCodeMason;
    private javax.swing.JButton btnCodeMonk;
    private javax.swing.JButton btnCodeParker;
    private javax.swing.JButton btnPlayArmstrong;
    private javax.swing.JButton btnPlayColtrane;
    private javax.swing.JButton btnPlayDavis;
    private javax.swing.JButton btnPlayEllington;
    private javax.swing.JButton btnPlayEvans;
    private javax.swing.JButton btnPlayHancock;
    private javax.swing.JButton btnPlayHoliday;
    private javax.swing.JButton btnPlayMason;
    private javax.swing.JButton btnPlayMonk;
    private javax.swing.JButton btnPlayParker;
    private javax.swing.JButton btnToArmstrong;
    private javax.swing.JButton btnToColtrane;
    private javax.swing.JButton btnToDavis;
    private javax.swing.JButton btnToEllington;
    private javax.swing.JButton btnToEvans;
    private javax.swing.JButton btnToHancock;
    private javax.swing.JButton btnToHoliday;
    private javax.swing.JButton btnToMason;
    private javax.swing.JButton btnToMonk;
    private javax.swing.JButton btnToParker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
