
import static cpt.CPT.playMusic;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 353365091
 */
public class FrmRockForm extends javax.swing.JFrame {

    //Declare public static String for main artists
    public static String rockSub;
    
    /**
     * Creates new form FrmRockForm
     */
    public FrmRockForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnBackToGenres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnToParamore = new javax.swing.JButton();
        btnToFoo = new javax.swing.JButton();
        btnCodeFoo = new javax.swing.JButton();
        btnPlayFoo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPlayParamore = new javax.swing.JButton();
        btnCodeParamore = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnToMetallica = new javax.swing.JButton();
        btnPlayMayer = new javax.swing.JButton();
        btnCodeMayer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnToFallOut = new javax.swing.JButton();
        btnPlayFallOut = new javax.swing.JButton();
        btnCodeFallOut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnToLinkin = new javax.swing.JButton();
        btnPlayLinkin = new javax.swing.JButton();
        btnCodeLinkin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnToWeezer = new javax.swing.JButton();
        btnPlayWeezer = new javax.swing.JButton();
        btnCodeWeezer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnToMayer = new javax.swing.JButton();
        btnPlayMetallica = new javax.swing.JButton();
        btnCodeMetallica = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnToFun = new javax.swing.JButton();
        btnPlayFun = new javax.swing.JButton();
        btnCodeFun = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnToGreenday = new javax.swing.JButton();
        btnPlayGreenday = new javax.swing.JButton();
        btnCodeGreenday = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnToPilots = new javax.swing.JButton();
        btnPlayPilots = new javax.swing.JButton();
        btnCodePilots = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 24, 24));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-20.png"))); // NOI18N
        btnBackToMenu.setContentAreaFilled(false);
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnBackToGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-library-20.png"))); // NOI18N
        btnBackToGenres.setContentAreaFilled(false);
        btnBackToGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToGenresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToGenres)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROCK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("choose your favourite artist from this genre.");

        btnToParamore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Paramore.jpg"))); // NOI18N
        btnToParamore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToParamoreActionPerformed(evt);
            }
        });

        btnToFoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Foo Fighters.jpg"))); // NOI18N
        btnToFoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToFooActionPerformed(evt);
            }
        });

        btnCodeFoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeFoo.setContentAreaFilled(false);
        btnCodeFoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeFooActionPerformed(evt);
            }
        });

        btnPlayFoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayFoo.setContentAreaFilled(false);
        btnPlayFoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayFooActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FOO FIGHTERS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PARAMORE");

        btnPlayParamore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayParamore.setContentAreaFilled(false);
        btnPlayParamore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayParamoreActionPerformed(evt);
            }
        });

        btnCodeParamore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeParamore.setContentAreaFilled(false);
        btnCodeParamore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeParamoreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("METALLICA");

        btnToMetallica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Metallica.jpg"))); // NOI18N
        btnToMetallica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMetallicaActionPerformed(evt);
            }
        });

        btnPlayMayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMayer.setContentAreaFilled(false);
        btnPlayMayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMayerActionPerformed(evt);
            }
        });

        btnCodeMayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMayer.setContentAreaFilled(false);
        btnCodeMayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMayerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FALL OUT BOY");

        btnToFallOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Fall Out Boy.jpg"))); // NOI18N
        btnToFallOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToFallOutActionPerformed(evt);
            }
        });

        btnPlayFallOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayFallOut.setContentAreaFilled(false);
        btnPlayFallOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayFallOutActionPerformed(evt);
            }
        });

        btnCodeFallOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeFallOut.setContentAreaFilled(false);
        btnCodeFallOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeFallOutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LINKIN PARK");

        btnToLinkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Linkin Park.jpg"))); // NOI18N
        btnToLinkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLinkinActionPerformed(evt);
            }
        });

        btnPlayLinkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayLinkin.setContentAreaFilled(false);
        btnPlayLinkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayLinkinActionPerformed(evt);
            }
        });

        btnCodeLinkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeLinkin.setContentAreaFilled(false);
        btnCodeLinkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeLinkinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("WEEZER");

        btnToWeezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Weezer.png"))); // NOI18N
        btnToWeezer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToWeezerActionPerformed(evt);
            }
        });

        btnPlayWeezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayWeezer.setContentAreaFilled(false);
        btnPlayWeezer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayWeezerActionPerformed(evt);
            }
        });

        btnCodeWeezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeWeezer.setContentAreaFilled(false);
        btnCodeWeezer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeWeezerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JOHN MAYER");

        btnToMayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/John Mayer.jpg"))); // NOI18N
        btnToMayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMayerActionPerformed(evt);
            }
        });

        btnPlayMetallica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayMetallica.setContentAreaFilled(false);
        btnPlayMetallica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayMetallicaActionPerformed(evt);
            }
        });

        btnCodeMetallica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeMetallica.setContentAreaFilled(false);
        btnCodeMetallica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMetallicaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FUN.");

        btnToFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Fun.jpg"))); // NOI18N
        btnToFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToFunActionPerformed(evt);
            }
        });

        btnPlayFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayFun.setContentAreaFilled(false);
        btnPlayFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayFunActionPerformed(evt);
            }
        });

        btnCodeFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeFun.setContentAreaFilled(false);
        btnCodeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeFunActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GREEN DAY");

        btnToGreenday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Greenday.jpg"))); // NOI18N
        btnToGreenday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToGreendayActionPerformed(evt);
            }
        });

        btnPlayGreenday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayGreenday.setContentAreaFilled(false);
        btnPlayGreenday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGreendayActionPerformed(evt);
            }
        });

        btnCodeGreenday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodeGreenday.setContentAreaFilled(false);
        btnCodeGreenday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeGreendayActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TWENTY ONE PILOTS ");

        btnToPilots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artistPhotos/rock/Twenty One Piolets.jpg"))); // NOI18N
        btnToPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToPilotsActionPerformed(evt);
            }
        });

        btnPlayPilots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-play-button-circled-20.png"))); // NOI18N
        btnPlayPilots.setContentAreaFilled(false);
        btnPlayPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPilotsActionPerformed(evt);
            }
        });

        btnCodePilots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-spotify-20.png"))); // NOI18N
        btnCodePilots.setContentAreaFilled(false);
        btnCodePilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodePilotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnToFoo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeFoo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayFoo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnToParamore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayParamore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeParamore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel3)
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnToMayer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayMayer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCodeMayer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnToFallOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCodeFallOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPlayFallOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnToLinkin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnPlayLinkin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnCodeLinkin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel7)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnToWeezer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnToGreenday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnPlayGreenday, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnCodeGreenday, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnToPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel12)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnCodeWeezer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPlayWeezer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addComponent(btnToMetallica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnCodeMetallica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPlayMetallica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnToFun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnPlayFun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnCodeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jLabel10))))
                                    .addComponent(btnCodePilots, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlayPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCodeMayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlayMayer))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(btnCodeParamore)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPlayParamore, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCodeFallOut)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPlayFallOut, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnToParamore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnToMayer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnToFallOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(btnCodeFoo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnPlayFoo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnToFoo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(btnCodeLinkin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnPlayLinkin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnToLinkin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnCodeFun)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPlayFun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnCodeGreenday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPlayGreenday, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnToGreenday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToWeezer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnToPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToMetallica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnToFun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnCodeMetallica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPlayMetallica, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnCodeWeezer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPlayWeezer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCodePilots)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlayPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCodePilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodePilotsActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\TwentyOnePilots.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodePilotsActionPerformed

    private void btnPlayPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPilotsActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\TwentyOnePilots.wav");
    }//GEN-LAST:event_btnPlayPilotsActionPerformed

    private void btnToPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToPilotsActionPerformed
        //Assign main artist name to public variable
        rockSub = "TWENTY ONE PILOTS";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToPilotsActionPerformed

    private void btnCodeGreendayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeGreendayActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\Greenday.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeGreendayActionPerformed

    private void btnPlayGreendayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayGreendayActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Greenday.wav");
    }//GEN-LAST:event_btnPlayGreendayActionPerformed

    private void btnToGreendayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToGreendayActionPerformed
        //Assign main artist name to public variable
        rockSub = "GREEN DAY";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToGreendayActionPerformed

    private void btnCodeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeFunActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\Fun.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeFunActionPerformed

    private void btnPlayFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayFunActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\fun.wav");
    }//GEN-LAST:event_btnPlayFunActionPerformed

    private void btnToFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToFunActionPerformed
        //Assign main artist name to public variable
        rockSub = "FUN.";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToFunActionPerformed

    private void btnCodeMetallicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMetallicaActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\Metallica.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMetallicaActionPerformed

    private void btnPlayMetallicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMetallicaActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Metallica.wav");
    }//GEN-LAST:event_btnPlayMetallicaActionPerformed

    private void btnToMayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMayerActionPerformed
        //Assign main artist name to public variable
        rockSub = "JOHN MAYER";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMayerActionPerformed

    private void btnCodeWeezerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeWeezerActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\Weezer.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeWeezerActionPerformed

    private void btnPlayWeezerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayWeezerActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Weezer.wav");
    }//GEN-LAST:event_btnPlayWeezerActionPerformed

    private void btnToWeezerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToWeezerActionPerformed
        //Assign main artist name to public variable
        rockSub = "WEEZER";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToWeezerActionPerformed

    private void btnCodeLinkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeLinkinActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\LinkinPark.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeLinkinActionPerformed

    private void btnPlayLinkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayLinkinActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\LinkinPark.wav");
    }//GEN-LAST:event_btnPlayLinkinActionPerformed

    private void btnToLinkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLinkinActionPerformed
        //Assign main artist name to public variable
        rockSub = "LINKIN PARK";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToLinkinActionPerformed

    private void btnCodeFallOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeFallOutActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\FallOutBoy.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeFallOutActionPerformed

    private void btnPlayFallOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayFallOutActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\FallOutBoy.wav");
    }//GEN-LAST:event_btnPlayFallOutActionPerformed

    private void btnToFallOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToFallOutActionPerformed
        //Assign main artist name to public variable
        rockSub = "FALL OUT BOY";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToFallOutActionPerformed

    private void btnCodeMayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMayerActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\JohnMayer.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeMayerActionPerformed

    private void btnPlayMayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayMayerActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\JohnMayer.wav");
    }//GEN-LAST:event_btnPlayMayerActionPerformed

    private void btnToMetallicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMetallicaActionPerformed
        //Assign main artist name to public variable
        rockSub = "METALLICA";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToMetallicaActionPerformed

    private void btnCodeParamoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeParamoreActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\Paramore.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeParamoreActionPerformed

    private void btnPlayParamoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayParamoreActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\Paramore.wav");
    }//GEN-LAST:event_btnPlayParamoreActionPerformed

    private void btnPlayFooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayFooActionPerformed
        //Call playMusic method from main class
        playMusic("src\\Audios\\FooFighters.wav");
    }//GEN-LAST:event_btnPlayFooActionPerformed

    private void btnCodeFooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeFooActionPerformed
        //Declare and initialize ImageIcon variable
        ImageIcon code = new ImageIcon("src\\codes\\FooFighters.jpg");
        
        //Output JOptionPane of Artist’s Spotify Code
        JOptionPane.showMessageDialog(null,"Scan this code on Spotify to\nlisten to more of this artist.","Spotify Code",JOptionPane.INFORMATION_MESSAGE,code);
    }//GEN-LAST:event_btnCodeFooActionPerformed

    private void btnToFooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToFooActionPerformed
        //Assign main artist name to public variable
        rockSub = "FOO FIGHTERS";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToFooActionPerformed

    private void btnToParamoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToParamoreActionPerformed
        //Assign main artist name to public variable
        rockSub = "PARAMORE";
        
        //Make sub genre form visible
        new FrmRockSub(rockSub).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnToParamoreActionPerformed

    private void btnBackToGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToGenresActionPerformed
        //Makes genres form visible
        new FrmGenresForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToGenresActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        //Makes menu form visible
        new FrmMenuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToGenres;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnCodeFallOut;
    private javax.swing.JButton btnCodeFoo;
    private javax.swing.JButton btnCodeFun;
    private javax.swing.JButton btnCodeGreenday;
    private javax.swing.JButton btnCodeLinkin;
    private javax.swing.JButton btnCodeMayer;
    private javax.swing.JButton btnCodeMetallica;
    private javax.swing.JButton btnCodeParamore;
    private javax.swing.JButton btnCodePilots;
    private javax.swing.JButton btnCodeWeezer;
    private javax.swing.JButton btnPlayFallOut;
    private javax.swing.JButton btnPlayFoo;
    private javax.swing.JButton btnPlayFun;
    private javax.swing.JButton btnPlayGreenday;
    private javax.swing.JButton btnPlayLinkin;
    private javax.swing.JButton btnPlayMayer;
    private javax.swing.JButton btnPlayMetallica;
    private javax.swing.JButton btnPlayParamore;
    private javax.swing.JButton btnPlayPilots;
    private javax.swing.JButton btnPlayWeezer;
    private javax.swing.JButton btnToFallOut;
    private javax.swing.JButton btnToFoo;
    private javax.swing.JButton btnToFun;
    private javax.swing.JButton btnToGreenday;
    private javax.swing.JButton btnToLinkin;
    private javax.swing.JButton btnToMayer;
    private javax.swing.JButton btnToMetallica;
    private javax.swing.JButton btnToParamore;
    private javax.swing.JButton btnToPilots;
    private javax.swing.JButton btnToWeezer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
